### ISSUE TITLE
ERROR: Service 'frontend' failed to build

### ISSUE THREAD

**Issue by stepfun** [thinkst/canarytokens-docker#10]
HI, I have issue while docker-compose up:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tIQTAC/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Xuy3Sd-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-tIQTAC/lxml/

ERROR: Service 'frontend' failed to build: The command '/bin/sh -c pip install --no-cache-dir lxml==3.4.4' returned a non-zero code: 1

Many thanks :)

**Comment by stepfun** [comment]
Any ideas where is problem?
Thanks.

**Comment by thinkst** [comment]
Hi @stepfun, could you give me a little more context so that I may help. Have you built the docker image yet? What version of docker are you using? I ask because the error suggests that the actual building of the image failed.

**Comment by obsti8383** [comment]
Same/similar problem here (Ubuntu 16.04.2 LTS with current docker from docker repo):

Output attached.
[lxml_error.txt](https://github.com/thinkst/canarytokens-docker/files/949016/lxml_error.txt)

**Comment by qeirik** [comment]
I can reproduce this with DO's smallest (512MB) droplet. Turns out it's a memory issue

http://stackoverflow.com/questions/24455238/lxml-installation-error-ubuntu-14-04-internal-compiler-error

Solution is to add some system memory, resizing image temporarily (during build) to 1GB works smoothly.

**Comment by thinkst** [comment]
@qeirik thanks for the update. @stepfun did @qeirik's suggested solution work? If not please let us know so we can dig into this further

**Comment by thinkst** [comment]
Haven't heard back about this issue. Closing it for now.
