### ISSUE TITLE
Nginx Bad Gateway after starting - failed while connecting upstream

### ISSUE THREAD

**Issue by 0x5h4un** [thinkst/canarytokens-docker#100]
Hi!

Please forgive me if I'm being stupid, but I have been trying to set up the docker containers in different environments now (locally, on university infrastructure and on DigitalOcean in a Droplet). However, every time I start up the containers and try to land on the homepage on IP_ADDR:80/generate, I get an HTTP 502 error from Nginx with the following message in the logs:

_connect() failed (113: No route to host) while connecting to upstream, client: <IP>, server: _, request: "GET /generate HTTP/1.1", upstream: "http://172.18.0.3:8082/generate", host: "subdomain.domainname"_

I've tried to change the Docker configuration to make sure I explicitly configure it to use my IPs among some other things like checking DNS, but I don't have enough experience with containerization to clearly see where this is going wrong (besides the DNS-related error). I did use a subdomain for the server, but I don't feel like that's the issue. Do you guys have any idea how to fix this or am I doing something horribly wrong?

Thanks a lot in advance!

**Comment by CTAA56** [comment]
I am actually having this same issue now. 
I have built this server multiple times earlier this year but didn’t receive the issue but now for some reason I get “(113:No route to host)
What did you do to resolve?

The server is built on a cloud instance

**Comment by 0x5h4un** [comment]
@CTAA56 Sorry for the late reply - make sure you include the WireGuard token as described in their documentation. After I did that, everything started working.
