### ISSUE TITLE
"Select your token" drop down has no item

### ISSUE THREAD

**Issue by gifrate** [thinkst/canarytokens-docker#109]
As the title says, the drop down on the /generate page does not show any items.

In the output logs, switchboard seems to be starting all the channels without issue.

I am at a loss as to where to look to fix the issue.

The network is air gapped for an exercise and I am using openSUSE Leap 15.3 if that helps

**Comment by jayjb** [comment]
Hi @gifrate,

Thanks for getting in touch. Can you confirm 
- that you are using the most recent docker images? 
- What docker commands are you using?
- If the frontend docker container is running without errors?
- if you open the dev tools for your browser when loading the canarytokens server, are there any errors in the console?

**Comment by jayjb** [comment]
Hi @gifrate,

We have made a bunch of improvements around UI and backend (with the upgrade to python3). I'm closing this issue for now. If you still hitting this issue, please reopen it.
