### ISSUE TITLE
DNS token not working

### ISSUE THREAD

**Issue by thryb** [thinkst/canarytokens-docker#11]
Good day,

I've setup canary token on an VPS instance and everything else but DNS seems to be working fine.

I pointed my domains Authoritative Name Servers to the IP (hostname cause IP gives me an error) where my docker instance is running but every time I try to dig a c token, it doesn't resolve. 

If I do:
#dig @canary_dns_or_ip (token).domain.com
Everything is working find and I get my DNS hit in my mail.

Any idea what could cause that problem?

Thanks a lot! Awesome work btw on that project :)

**Comment by thryb** [comment]
The first registrar I was using for some reason didn't play well with the NS. 

I used google domain with other domains and it works perfectly.

**Comment by jaswinder97** [comment]
@thryb could you please explain what was the issue ?
