### ISSUE TITLE
Nginx redirect to HTTPS

### ISSUE THREAD

**Issue by marcogiorgio** [thinkst/canarytokens-docker#118]
Hi,
I deployed Canarytokens using the HTTPS route. It all works correctly but I noticed that HTTP requests aren't redirected to HTTPS. Wouldn't be better to edit the default nginx.conf file in order to have HTTPS only?
Thanks

**Comment by JStyle21** [comment]
+1

**Comment by ranok** [comment]
This should be fixed now with the 301 to https in certbot-nginx/nginx.conf
