### ISSUE TITLE
Word safty view not triggering token

### ISSUE THREAD

**Issue by mrrobotnl** [thinkst/canarytokens-docker#119]
Hey Canarytokens (and community), 
I am currently working with your framework and installed the framework via docker. It worked fine until a few weeks ago, I see that especially office documents do not trigger anymore if they open in safe view. 
Is this problem already known or and is there a current work around that I could use?

**Comment by jayjb** [comment]
Hi @mrrobotnl 

The safety mode has stopped the tokens from triggering in some versions of MS Word. We are looking at methods around this.

**Comment by jayjb** [comment]
Closing this issue as it is based on research we will be doing on the MS Word Canarytoken.
