### ISSUE TITLE
service_identity module

### ISSUE THREAD

**Issue by residentialflipper** [thinkst/canarytokens-docker#13]
I have installed the canarytokens-docker in a few different ways (the way i install docker and docker-compose) but it never connects to my mailgun account. 

In all instances i'am getting this error:

 :0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

I tries different ways of installing and updating  the service_identity module, and i'm getting this reply:

pip install --upgrade service_identity
Requirement already up-to-date: service_identity in /usr/local/lib/python2.7/dist-packages/service_identity-16.0.0-py2.7.egg
Requirement already up-to-date: attrs in /usr/local/lib/python2.7/dist-packages/attrs-16.3.0-py2.7.egg (from service_identity)
Requirement already up-to-date: pyasn1 in /usr/local/lib/python2.7/dist-packages (from service_identity)
Requirement already up-to-date: pyasn1-modules in /usr/local/lib/python2.7/dist-packages/pyasn1_modules-0.0.8-py2.7.egg (from service_identity)
Requirement already up-to-date: pyopenssl>=0.12 in /usr/local/lib/python2.7/dist-packages (from service_identity)
Requirement already up-to-date: cryptography>=1.3.4 in /usr/local/lib/python2.7/dist-packages (from pyopenssl>=0.12->service_identity)
Requirement already up-to-date: six>=1.5.2 in /usr/lib/python2.7/dist-packages (from pyopenssl>=0.12->service_identity)
Requirement already up-to-date: setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl>=0.12->service_identity)
Requirement already up-to-date: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl>=0.12->service_identity)
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl>=0.12->service_identity)
Requirement already up-to-date: idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl>=0.12->service_identity)
Requirement already up-to-date: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4->pyopenssl>=0.12->service_identity)
Requirement already up-to-date: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from setuptools>=11.3->cryptography>=1.3.4->pyopenssl>=0.12->service_identity)
Requirement already up-to-date: packaging>=16.8 in /usr/local/lib/python2.7/dist-packages (from setuptools>=11.3->cryptography>=1.3.4->pyopenssl>=0.12->service_identity)
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography>=1.3.4->pyopenssl>=0.12->service_identity)
Requirement already up-to-date: pyparsing in /usr/local/lib/python2.7/dist-packages (from packaging>=16.8->setuptools>=11.3->cryptography>=1.3.4->pyopenssl>=0.12->service_identity)

**Comment by mamisano** [comment]
Encountering the same issue on Ubuntu 16.04. This worked fine on my MacBook Pro but not on Ubuntu.

**Comment by psifertex** [comment]
`service_identity` isn't required for it to work -- was that the only part of the error you get while running it?   I just got it up and going on an EC2 Amazon Linux instance without too much trouble though initially I had an empty NXDOMAIN variable that was causing trouble. I thought at first that `service_identity` was the trouble because of the warnings, but after more closely reading the error output, realized that wasn't the case.

**Comment by mamisano** [comment]
I got it up and running on Ubuntu 14.04 now - 16.04 was just giving me too many headaches. I do have another issue in that there is no history when I check a token after being triggered. Not sure if it is related to this or not.

**Comment by residentialflipper** [comment]
Thanks for the replies, i'am looking into the NXDOMAIN variable, i'am only using 1 domain so my fronted.env looks like:

CANARY_DOMAINS=domain.xx
CANARY_NXDOMAINS=domain.xx
CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads

and my switchboard.env looks like:

CANARY_MAILGUN_DOMAIN_NAME=https://api.mailgun.net/v3/mg.domain.xx/messages
CANARY_MAILGUN_API_KEY=key-0aaxxxxxxxxxxxxxxxxx
#CANARY_MANDRILL_API_KEY=
CANARY_PUBLIC_IP=zz.zz.zz.zz
CANARY_PUBLIC_DOMAIN=domain.xx
CANARY_ALERT_EMAIL_FROM_ADDRESS=noreply.domain.xx
CANARY_ALERT_EMAIL_FROM_DISPLAY="CanaryAlert"
CANARY_ALERT_EMAIL_SUBJECT="CanaryToken"
CANARY_TOKEN_RETURN=fortune
CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads

I tested the mailgun account with  the perl script and it works.
Does anybody see any faults?

**Comment by residentialflipper** [comment]
I did an reinstall on ubuntu 14.04 LTS, besides the service_identity module error I get an TCP backlog warning and an No handlers could be found for logger "generator_httpd" notification.
Thanks for helping out!

**Comment by residentialflipper** [comment]
Finally figured is out, i made an mistake in the CANARY_MAILGUN_DOMAIN_NAME, i only needed to fill in the mailgun domain name: mg.domain.xx instead of the complete link; example:

CANARY_MAILGUN_DOMAIN_NAME=mg.domain.xx
CANARY_MAILGUN_API_KEY=key-0aaxxxxxxxxxxxxxxxxx
#CANARY_MANDRILL_API_KEY=
CANARY_PUBLIC_IP=zz.zz.zz.zz
CANARY_PUBLIC_DOMAIN=domain.xx
CANARY_ALERT_EMAIL_FROM_ADDRESS=noreply@domain.xx
CANARY_ALERT_EMAIL_FROM_DISPLAY="CanaryAlert"
CANARY_ALERT_EMAIL_SUBJECT="CanaryToken"
CANARY_TOKEN_RETURN=fortune
CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads

Thanks for all the help!
