### ISSUE TITLE
Remove/delete a single token?

### ISSUE THREAD

**Issue by jeffshead** [thinkst/canarytokens-docker#130]
I know you can remove all tokens by deleting `/data/dump.rdb`.
I want to delete a single token and keep the rest. Is this possible? If so, can someone please share the commands?

**Comment by thinkst-pieter** [comment]
Hi @jeffshead.

Thanks for writing in.

> I want to delete a single token and keep the rest.

Yes, it is possible.

Prerequisites:
1. SSH Access to the docker host
2. User account to access the server
3. TOKEN ID for the token you wan't to delete. You can find it on the management page of the token.

Steps:
```
$ ssh <<TOKEN HOST>>
$ docker exec -it redis redis-cli
$ hgetall canarydrop:<<TOKEN ID>>  # This verifies the token exists before deleting (Less overhead than doing $ keys *<<TOKEN ID>>*
$ del canarydrop:<<TOKEN ID>>  # (Integer 1) confirms that the token was deleted correctly.
```

If you wan't do disable the token and keep its history you can just make use of the management page to disable the alerts for the token.

**Comment by jeffshead** [comment]
Thank you!
