### ISSUE TITLE
frontend' failed to build

### ISSUE THREAD

**Issue by Manu-Surendra** [thinkst/canarytokens-docker#14]
This is the error tht i receive. Any thoughts on this guys?

Could not find a version that satisfies the requirement setuptools (from versions: )
No matching distribution found for setuptools
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c pip install -U setuptools' returned a non-zero code: 1

**Comment by Manu-Surendra** [comment]
figured out the issue. I missed a few steps

**Comment by phongiswindy** [comment]
GOT this same error. What did you do to fix it?

> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Msx1eu/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6fahGL-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Msx1eu/lxml/
> ERROR: Service 'frontend' failed to build: The command '/bin/sh -c pip install --no-cache-dir lxml==3.4.4' returned a non-zero code: 1
