### ISSUE TITLE
Running with Docker-compose ends up with a lot of errors

### ISSUE THREAD

**Issue by B-Esmaili** [thinkst/canarytokens-docker#157]
**Describe the bug**
When running with docker-compose  a lot of errors occur. 

**To Reproduce**
1 - clone the repo
2 - prepare the env files
3- run docker-compose up

**Expected behavior**
the program should come up

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux mint 21
 - Browser [chrome]

**Additional context**
Add any other context about the problem here. Suggested additional information
- Running in docker? docker version 24

All of services encounter error. following is error message for each service : 

# Switchboard
` No such file or directory: 'switchboard.tac`

# FrontEnd 
`No such file or directory: 'frontend.tac'`

# nginx 

`"server" directive is not allowed here in /etc/nginx/conf.d/default.conf:1`

**Comment by B-Esmaili** [comment]
@jayjb Thanks for your solution. i tried v3 and it did work. strangely  i remember that i had tried it out and it didn't work , but this time it is working.

**Comment by jayjb** [comment]
@B-Esmaili, ah thats a relief. Sorry for the confusion. We'll get on sorting that out.
