### ISSUE TITLE
Canary Token conflicts with already running service in port 53 in ubuntu

### ISSUE THREAD

**Issue by B-Esmaili** [thinkst/canarytokens-docker#161]
**Describe the bug**
When we start the docker-compose service of canary token it wouldn't start because of already running dns service in ubuntu.

**To Reproduce**
1 - run docker-compose up

**Expected behavior**
the service should start.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux(Ubunut)
 - Browser Chrome
 - Version 22

**Additional context**
Add any other context about the problem here. Suggested additional information
- Running in virtualenv? No
- Running in docker? Yes. Docker 21

What is the recommended solution for this problem?

**Comment by jayjb** [comment]
Hi @B-Esmaili,

We have seen something similar on Ubuntu 18.04 (documented over [here](https://github.com/thinkst/canarytokens-docker/wiki#name-resolution-is-failing-on-ubuntu-1804)). The just is that Ubuntu runs `systemd-resolved` by default. Would you mind trying the following commands:
```
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
```

**Comment by B-Esmaili** [comment]
Thanks @jayjb the second solution worked for me.
