### ISSUE TITLE
Support for Load Balancer DNS Record in CANARY_PUBLIC_IP

### ISSUE THREAD

**Issue by alitavakoli-moonfare** [thinkst/canarytokens-docker#170]
**Description**:
In the current implementation of Canary Token's frontend and switchboard environment variables, `CANARY_PUBLIC_IP` only accepts IP addresses. However, in real EKS environments, the IP address of the load balancer can change dynamically, and we may not have control over it.

**Proposal:**
To address this limitation and provide more flexibility, we propose adding support for load balancer DNS records in the `CANARY_PUBLIC_IP` environment variable or adding a new value like `CANARY_PUBLIC_DNS`. This would allow users to specify a DNS record that resolves to the load balancer's IP address instead of hardcoding the IP address directly.

**Comment by mclmax** [comment]
Hi @alitavakoli-moonfare,

Taking a quick look it seems we use the public IP address to setup the DNS records (specifically NS / A records) used to facilitate triggering a token. We'd need to give this some thought if we were to change it.

Have you tried to assign an Elastic IP address to the load balancer? The IP would be static and should work.

**Comment by alitavakoli-moonfare** [comment]
Thanks for your response. While Elastic IP is an option, it's not straightforward to change the production EKS. Additionally, relying on DNS instead of IP addresses offers greater flexibility. I suggest including another record, like CANARY_PUBLIC_DNS, which can be utilized for scenarios such as the kubectl API server IP or if they are hardcoded in the .pdf and .docx files as tokens.

**Comment by mclmax** [comment]
Unfortunately supporting Kubernetes isn't something we plan on doing. We don't want to add too much complexity here. 

You're welcome to hack on this stuff to fit your needs but it's not something we'll be supporting.
