### ISSUE TITLE
 Enhance CanaryToken to Capture Real User IP and Extract More Values

### ISSUE THREAD

**Issue by alitavakoli-moonfare** [thinkst/canarytokens-docker#171]
**Description**:
Currently, in our EKS environment, when tokens such as WebBug, FastRedirect, and SlowRedirect are invoked, the reported source IP does not reflect the real public IP of the user who clicked on the link. Instead, it shows the IP address of the Ingress pod. Additionally, it appears that we're not extracting as much value from the user as desired.

**Challenges**:

**Inaccurate Source IP**: The reported source IP does not accurately reflect the real public IP of the user, making it challenging to attribute actions to specific users.
**Limited User Data Extraction**: The amount of data extracted from the user's interaction is insufficient for our needs, limiting the effectiveness of the CanaryToken.

**Proposed Enhancements**:

**Capture Real User IP**: Modify CanaryToken to capture the real public IP address of the user who interacts with the token. 

![Screenshot 2024-02-08 at 15 36 25](https://github.com/thinkst/canarytokens-docker/assets/97187758/2b0ece41-f44f-4c9c-a91e-f50caeb03404)
![Screenshot 2024-02-08 at 15 36 39](https://github.com/thinkst/canarytokens-docker/assets/97187758/ccc3e83e-0cfb-4c96-857c-27e83e3e2a21)
![Screenshot 2024-02-08 at 15 37 01](https://github.com/thinkst/canarytokens-docker/assets/97187758/c49cc55a-b5eb-411d-8fc1-09faae4dc0cf)

**Comment by mclmax** [comment]
Hi @alitavakoli-moonfare,

Thanks for writing in.

Is the `X-Original-Forwarded-For` IP address what you're looking for here? That should be the original IP address of the request?

If so we can add this to our stack to get that header value set as the trigger IP.

**Comment by alitavakoli-moonfare** [comment]
Yes True. That is the real original IP that can be used.
