### ISSUE TITLE
[BUG] Certbot ignores start.sh

### ISSUE THREAD

**Issue by Tahir-ShiftCTRL** [thinkst/canarytokens-docker#180]
**Describe the bug**
When launching docker-compose-letsencrypt.yml, let's encrypt tries to get certs for domain.com and www.domain.com. If you modify start.sh and remove " -d www.${MY_DOMAIN_NAME}" from the _args, nothing changes. If I add --staging to the certbot line, nothing it still tries to issue a real cert. If I completely delete the start.sh file, nothing changes, it still tries to issue a real cert with the domain.com and www.domain.com

**To Reproduce**
1. delete start.sh
2. run docker compose -f docker-compose-letsencrypt.yml up -d
3. check docker logs nginx

**Expected behavior**
Certs should not be issued

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by jayjb** [comment]
Hi @Tahir-ShiftCTRL,

Thanks for reporting this. I think I have an idea of what might be going wrong. Can you quickly confirm something for me - when you say `delete start.sh`, where are you deleting it? 

The reason I ask is that if you are using the docker images (i.e. not building your own), then the docker image will contain the `start.sh`; if you have cloned the repo and run `docker compose -f docker-compose-letsencrypt.yml up -d`, then the `start.sh` that is being run, is the `start.sh` that is inside the docker container.

**Comment by jayjb** [comment]
Hi @Tahir-ShiftCTRL,

Please let me know about the above questions when you have a moment.

**Comment by Tahir-ShiftCTRL** [comment]
I'm referring to cloned file (not the one inside the container). 

That would explain why modifying the file has no impact on the outcome, though that's a very strange way of setting it up. The host file should be bound to the container file.

> Hi @Tahir-ShiftCTRL,
> 
> Please let me know about the above questions when you have a moment.

**Comment by jayjb** [comment]
Hi @Tahir-ShiftCTRL,

That file is built into the container so that we don't need to map the container's filesystem to your local machine's filesystem in order to run the container. 

It means that the container is more portable because it contains all the files it needs - so if you decide to pull the container from the docker registry (rather than cloning the repo), you will have everything you need.

But I am glad we have figured it out.
