### ISSUE TITLE
[BUG] Self hosted Cloud Flare Tunnel not working. 

### ISSUE THREAD

**Issue by gru3zi** [thinkst/canarytokens-docker#182]
**Describe the bug**

On the older version of canary tokens I was able to get it working through a cloudflare tunnel but now its stopped working. 

Link: https://b1rdie.online/nest/

I can access the main page but when I try to test something I get a 404. 

![image](https://github.com/user-attachments/assets/ce30363d-1273-45ac-856a-e25c8a8c96b9)

![image](https://github.com/user-attachments/assets/5f591b9f-c5c1-4761-a09f-5a2f117eda15)

**Expected behavior**

should not be getting a 404. 

**Desktop (please complete the following information):**
 - OS: Proxmox Linux Container  (Linux CanaryBird 6.2.16-12-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-12 (2023-09-04T13:21Z) x86_64 x86_64 x86_64 GNU/Linux)

**Additional context**

I forwarded my dns to cloud flare and setup a tunnel from there. 

![image](https://github.com/user-attachments/assets/227eb4e2-1a08-48d6-bfdb-cf56d29f6419)

***

**frontend.env**

CANARY_DOMAINS=b1rdie.online
CANARY_NXDOMAINS=token.b1rdie.online
CANARY_PUBLIC_IP=192.168.15.163

CANARY_GOOGLE_API_KEY=<redacted>
CANARY_WG_PRIVATE_KEY_SEED=<redacted>

CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads
#Enter number so 1024*1024*10 = 10485760
CANARY_MAX_UPLOAD_SIZE=10485760

LOG_FILE=frontend.log

***

**switchboard.env**     
                                                                                      
#CANARY_MAILGUN_DOMAIN_NAME=
#CANARY_MAILGUN_API_KEY=
#CANARY_MANDRILL_API_KEY=
#CANARY_SENDGRID_API_KEY=
CANARY_PUBLIC_IP=192.168.15.163
CANARY_PUBLIC_DOMAIN=b1rdie.online
CANARY_ALERT_EMAIL_FROM_ADDRESS=<redacted>
CANARY_ALERT_EMAIL_FROM_DISPLAY="CANARY MAILER"
CANARY_ALERT_EMAIL_SUBJECT="ALERT"
CANARY_MAX_ALERTS_PER_MINUTE=1000
CANARY_SMTP_USERNAME=<redacted>
CANARY_SMTP_PASSWORD=<redacted>
CANARY_SMTP_SERVER=smtp.gmail.com
CANARY_SMTP_PORT=587
CANARY_IPINFO_API_KEY=<redacted>

CANARY_TOKEN_RETURN=fortune
CANARY_WG_PRIVATE_KEY_SEED=<redacted>

CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads

LOG_FILE=switchboard.log

# Default protocol to use in notification links. If you don't use LetsEncrypt, set to http
PROTOCOL=https
ERROR_LOG_WEBHOOK=

***

Could you please let me know if i'm doing something wrong?

**Comment by thinkst-daniel** [comment]
Hi @gru3zi,

Thanks for writing in and for raising this. I've deployed a similar setup to yours using Cloudflare tunnels, and I also get the same issue when the token URL ends in `.js`. If I use something else, such as`*.gif` for the same token ID however, then I do see the alert.

Are you only having issues with `.js`, or all URLs for that token ID? I'm diving deeper on my side in the meantime to look for a fix.

**Comment by thinkst-daniel** [comment]
Hi @gru3zi,

Thanks for the update. I've had another look and re-deployed all canarytoken containers, as well as the latest `cloudflared` docker tunnel too. Since then I'm not having any issues with `/.js` URLs.

Do you mind sharing which `cloudflared` version/tag version you are running, as well as an output of your Canarytokens server at the time of when you try and trigger the token? Thanks!

**Comment by gru3zi** [comment]
![image](https://github.com/user-attachments/assets/f4bba272-cb7d-413d-bf60-d9c6e69cfddc)

Version - 2024.9.1

![image](https://github.com/user-attachments/assets/55b80354-8982-435a-bf3b-ac4d558e45c4)

![image](https://github.com/user-attachments/assets/d3e63fdb-c13a-4418-bfe5-55bd04f7902f)

I tested the link but doesnt look like much output from the docker logs

![image](https://github.com/user-attachments/assets/829efac3-08c7-4bdc-b2de-b3cd8f89abf6)

**Comment by thinkst-daniel** [comment]
Hi @gru3zi,

Sorry about the delay here and thanks for sending this through.

Would it be possible to see the logs from the `nginx` (`thinkst/canarytokens_ngninx` image) and `switchboard` (`thinkst/canarytokens` image) containers too? Those will give us a better indication of how/where the request is possibly breaking. Easiest way would be to kill all of the `canarytoken` containers and re-run `docker compose up` and look at the output of logs there. That will also help to confirm if there are no issues with any of them starting up too.

I am also curious to know if you're running the Cloudflare connector container on the same host as the Canarytokens services and in which order you've fired those containers up? Your connector version looks fine to me.
