### ISSUE TITLE
Manage your settings for this Canarydrop URL

### ISSUE THREAD

**Issue by n0x00** [thinkst/canarytokens-docker#2]
hey guys, really cool !

I have the docker instance nearly fully configured, one thing i noticed is that the url given by canarydrop is still tied to http://canarytokens.org 

so, if i have it set up on abc123.com in my email I will see 

`One of your canarydrops was triggered.

Channel: HTTP
Time   : 2015-11-27 04:21:44.045019
Memo   : lol
Source IP : 127.0.0.1
User-agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)

Manage your settings for this Canarydrop:
http://canarytokens.org/manage?token=fgmb0x5iy3s29rkdhvrvq8cm1&auth=eca1a0a47c8ce7d0704758b6c920733f `

and perhaps it should be 

`One of your canarydrops was triggered.

Channel: HTTP
Time   : 2015-11-27 04:21:44.045019
Memo   : lol
Source IP : 127.0.0.1
User-agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)

Manage your settings for this Canarydrop:
http://abc123.com/manage?token=fgmb0x5iy3s29rkdhvrvq8cm1&auth=eca1a0a47c8ce7d0704758b6c920733f  `

**Comment by HostOnNet** [comment]
I have same problem, any fix for this ? The code is on

https://github.com/thinkst/canarytokens/blob/master/channel.py#L37

It will be nice if docker file system get mounted on host for such quick fix until it get fixed in repo.

**Comment by thinkst** [comment]
Hey @HostOnNet and @n0x00,

Sorry for the massively delayed response (we wont drop the ball again!). We have fixed this issue. Thanks for pointing it out!
