### ISSUE TITLE
How to setup https with letsencrypt yml file

### ISSUE THREAD

**Issue by smehta1215** [thinkst/canarytokens-docker#20]
Hi! I want to use the docker-compose-letsencrypt.yml for https but I'm not sure how to do so - can anyone help and give some instructions on how to get that set up?

**Comment by x011** [comment]
I also would like to know this...
It's a shame this project died before achieved, at least, a stable and workable version.

**Comment by ozskywalker** [comment]
Time to fork it?

//LW

________________________________

**Comment by haroon-meer** [comment]
I have 2 thoughts here:
1) The project is very much alive.. The live site at https://Canarytokens.org runs a copy of this code and is used by thousands of people every month;
2) The docker images are deployed at a bunch of 3rd party sites pretty successfully;
3) While its completely your prerogative, maybe consider a PR before a fork? I.e. part of the joy of open source is that you can actually contribute?

**Comment by thinkst** [comment]
Hey @x011, @smehta1215 and @ozskywalker,

We are so sorry for the delayed response (we won't drop the ball again!). We are putting together some notes (which will join repo soon) on how to setup your Canarytokens docker with lets-encrypt. 

Thanks for taking an interest in our project and we look forward to getting you up and running (HTTPS style!)

**Comment by thinkst** [comment]
Hey @x011, @smehta1215 and @ozskywalker,

We have added some new support for running an HTTPS version of Canarytokens (still using lets-encrypt). Please give it a whirl. Thank you for your patience and I look forward to hearing from you.

**Comment by obsti8383** [comment]
HTTPS workes fine on my installation (at least when considering the fixed typing error in README.md, see #28 ). Thanks a lot @thinkst .
