### ISSUE TITLE
Subdomain as 2nd domain & Token History

### ISSUE THREAD

**Issue by x011** [thinkst/canarytokens-docker#24]
Hi there,

> "_At least one domain name. If you want to enabled PDF-opening tracking, at least two domains._"
Can we use a subdomain as 2nd domain?

I'm having some issues with tokens history. If I click on `More info on this token here` on the email containing the alert, I'm redirected to a page (ps below) but cannot see any history 
.Is this normal or am I missing something?

![ss_463](https://user-images.githubusercontent.com/4313821/39393325-fbe95066-4abb-11e8-9fab-c41f223fb63e.jpg)

Thank you.

**Comment by thinkst** [comment]
Hey @x011,

This is not expected behaviour. Which token type did you create? I also notice (from the image) that this is a private Canarytokens server. Are you the one running it? (otherwise there may have been other modifications to whatever code is running that server)

**Comment by thinkst** [comment]
Hey @x011,

I just wanted to ping you quickly with that subdomains are currently supported as a 2nd domain (but it is a good idea and it is something we will add to out TODO list).

 If you let me know about the above information that would be super helpful. I have tried to replicate the issue, but with no success (my alerts appear in the history). To this end, would you mind giving me some more information/context regarding this Canarytokens server?

Thanks for taking an interest and i hope we can get it up and running properly soon.

**Comment by thinkst** [comment]
Hey @x011,

I just wanted to ping you and say we have made some changes to the canarytokens code. So if you wouldn't mind pulling and rebuilding the image, your issue should be resolved.

Thanks for your patience and input
