### ISSUE TITLE
email notification

### ISSUE THREAD

**Issue by aalloosshh** [thinkst/canarytokens-docker#25]
Why don't I receive email notifications from Canarytokens-docker? 
i have one docker domain, and when someone use tracking link or any other option, he don't receive email report.
can you help me??
thx

**Comment by thinkst** [comment]
Hey @aalloosshh,

Im sorry that the emails aren't coming through. For the email facility to work, you must supply an API key for the supported email services (Sendgrid, Mailgun or Mandrill). Have you done this? You can insert the API key in the `switchboard.env` file and restart the docker instance. 

I hope this helps. Please let me know if I can help you further.

**Comment by aalloosshh** [comment]
hey @thinkst 
thx for your replay
i have mailgun account and it is work and i had tried with api test send mail and it work great
but i still not to receive email notification
an i can't understand where is my fault

nots:   i have this warning message:

redis          | 1:M 16 Jul 12:58:33.700 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

switchboard    | :0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

but i installed pip install service_identity and execute this command
echo 65535 > /proc/sys/net/core/somaxconn
but still have this warning
my switchboard file contain
CANARY_MAILGUN_DOMAIN_NAME=mg.mydomain.com
CANARY_MAILGUN_API_KEY=key-xxxxxxxxxxxxxxxxxxxxx-xxxxxx-xxxxxx
CANARY_PUBLIC_IP=xx.xx.xx.xx
CANARY_PUBLIC_DOMAIN=mydomain.com
CANARY_ALERT_EMAIL_FROM_ADDRESS=name@mydomain.com
CANARY_ALERT_EMAIL_FROM_DISPLAY="Example"
CANARY_ALERT_EMAIL_SUBJECT="Token"

so have i any problem with this file ??

**Comment by aalloosshh** [comment]
another question plz
in switchboard file
the api key from mailgun should be private key oder public key?
thx
BR
