### ISSUE TITLE
docker container not starting up

### ISSUE THREAD

**Issue by obsti8383** [thinkst/canarytokens-docker#26]
Hi, the newest version of the docker container does not start up on my server (AWS Ubuntu Linux) anymore.

"frontend" and "switchboard" continue restarting and contain errors regarding the log.logger in twistd.

Only after editing the yml and removing the log sections it starts up normally.

DIFF:
diff --git a/docker-compose.yml b/docker-compose.yml
index 51faf74..9a3a743 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -17,9 +17,8 @@ services:
      - frontend.env
     volumes:
     - ./uploads:/uploads/
-    - log-volume:/logs
     container_name: frontend
-    command: bash -c "rm frontend.pid; twistd -noy frontend.tac --logger log.logger --pidfile=frontend.pid"
+    command: bash -c "rm frontend.pid; twistd -noy frontend.tac --pidfile=frontend.pid"
   switchboard:
     build: ./canarytokens/
     restart: always
@@ -35,7 +34,7 @@ services:
     volumes_from:
     - frontend
     container_name: switchboard
-    command: bash -c "rm switchboard.pid; twistd -noy switchboard.tac --logger log.logger --pidfile=switchboard.pid"
+    command: bash -c "rm switchboard.pid; twistd -noy switchboard.tac --pidfile=switchboard.pid"
   nginx:
     restart: always
     image: thinkst/canarytokens_nginx
@@ -47,5 +46,3 @@ services:
      - switchboard
     container_name: nginx
     command: /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
-volumes:
-  log-volume:

**Comment by thinkst** [comment]
Hey @obsti8383,

Thanks for the pull request (and well spotted!). We have accepted it! With regards to this issue, have you resolved it or is it ongoing? If not, let me know how I can help (and ill dive a little deeper into why this is happening).

**Comment by obsti8383** [comment]
Hi @thinkst 

I think this is not resolved, since removing all the logging things in my local yml is not the solution. Are the containers starting up on other installations using the settings as they are in the github repository?

My pull request didn't contain these changes I made.

Thanks
Florian

**Comment by thinkst** [comment]
Hey @obsti8383,

Im sorry you having issues getting this up and running. I quickly tested a completely vanilla version of Canarytokens on an AWS instance and it seemed to start fine. Could I ask you to do a `docker-compose rm`, then delete the old images entirely. Once that is done, try `docker-compose up` and let them build and pull the new images please.

**Comment by obsti8383** [comment]
Hi @thinkst : You are right. I was quite sure that i did that already. This time I cleaned up everything an started with a clean git export and that worked like a charm.

Sorry for that. I'am closing the issue.

Keep up the good work and thanks a lot.
