### ISSUE TITLE
Systemd and a blocked/already in use port 53

### ISSUE THREAD

**Issue by nielsduelund** [thinkst/canarytokens-docker#29]
Hi
Previously I have installed the Docker image on Ubuntu 16.04, where it
works. To be compliant though, it has to run on 18.04.
I know the following may not be caused by your software, but I must admit that I'm unable to solve it myself so I have to ask ...
I installed the server a few days ago, so the software is brand new from github (both canarytokens and canarytokens-docker).

The problem is a clash between the Canary software which listens to port 53, and systemd-resolved, that does the same.
The symptom is seen in:
   docker-compose up
      ...
      ...
      Starting frontend ... done
      Starting switchboard ... 
      Starting switchboard ... error

      ERROR: for switchboard  Cannot start service switchboard: driver
      failed programming external connectivity on endpoint switchboard
      (c914c1d34eb093d9e0b6ecc3354cdf7dac94a55fbeec103aa433f6f295a6c235):
      Error starting userland proxy: listen **tcp 0.0.0.0:53: bind: address
      already in use**

      ERROR: for switchboard  Cannot start service switchboard: driver
      failed programming external connectivity on endpoint switchboard
      (c914c1d34eb093d9e0b6ecc3354cdf7dac94a55fbeec103aa433f6f295a6c235):
      Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address
      already in use
      ERROR: Encountered errors while bringing up the project.

"Who" is using the port ?
   fuser 53/tcp
      53/tcp:               5138

   ps -ef | grep 5138
      systemd+  5138     1  0 10:10 ?        00:00:00 /lib/systemd/systemd-resolved
      root      5161  3920  0 10:10 pts/0    00:00:00 grep --color=auto 5138

So systemd-resolved is using the port !!

I have found solutions that tells me to edit /etc/systemd/resolved.conf and disable the DNSStubListener. I set
   DNSStubListener=no
and restart systemd-resolv
   systemctl restart systemd-resolved

What this does it that it DOES allow me to start the canary application, but it ALSO results in that DNS resolution on the host no longer works.
ping github.com
   ping: github.com: Temporary failure in name resolution

By examining the output.txt file (generated by channel_dns.py) i see
   Query('check.torproject.org', 1, 1)
   Query('check.torproject.org', 1, 1)
   Query('check.torproject.org', 1, 1)
   Query('check.torproject.org', 1, 1)
   Query('github.com', 1, 1)
   Query('github.com', 28, 1)
   Query('github.com', 1, 1)
   Query('github.com', 28, 1)
   Query('ubuntu.com', 1, 1)
   Query('ubuntu.com', 28, 1)
so the docker image DOES pick up requests made on the host.

It may be a side track, but I think, that channel_dns.py should handle 
requests made on the host. Has it anything to do with the commented call
to _do_dynamic_response?

Kind regards Niels

**Comment by ndom91** [comment]
In the docker-compose.yml file I simply changed 53:53 to 54:53 so that it binds to port 54 on the outside and forwards it to 53 on the inside.

Im not using DNS Tokens so that was it for me. It was able to build then at least. In order ot get DNS Tokens to work again, that is another issue :smile:

**Comment by thinkst** [comment]
Hey @nielsduelund, @ndom91 

Sorry for the delay. The workaround here is,

1. disable `systemd-resolvd`
2. remove the `/etc/resolv.conf` symlink (maybe back it up)
3. create new `/etc/resolv.conf` with contents pointing towards your favourite DNS. My `/etc/resolv.conf` has `nameserver 8.8.8.8` in it. 

Please let me know if you would like more of a description of the issue and how it is solved.

**Comment by nielsduelund** [comment]
Thanks for your reply. I may try it out at some tine, but for now I have swapped to using a Kali 18.04 instead of a lUbuntu 18.04. For some reason Kali works differently in this respect.
Please keep this thread for future reference for others. I have spent many hours of reinstalling because I thought i did something wrong.
Thanks for a great product :-)

**Comment by thinkst** [comment]
hey @nielsduelund,

Thats great 👍 Glad it is working.

**Comment by jayjb** [comment]
Closing issue because we found a good work around. Ill add the workout to the wiki for known issues with work arounds (when we get to that).

**Comment by mrrobotnl** [comment]
> 
> 
> In the docker-compose.yml file I simply changed 53:53 to 54:53 so that it binds to port 54 on the outside and forwards it to 53 on the inside.
> 
> Im not using DNS Tokens so that was it for me. It was able to build then at least. In order ot get DNS Tokens to work again, that is another issue 😄

Your a real legend, I was fighting this work around for a whole day now, I saw your solution great thanks
