### ISSUE TITLE
mailgun domain name

### ISSUE THREAD

**Issue by rayda** [thinkst/canarytokens-docker#3]
have managed to get the docker image running, however am not receiving emails. 

in the switchboard.env can an example be provided for the parameter

if my parent domain is xyz.com what should

canary_mailgun_domain_name=

**Comment by thinkst** [comment]
Hi rayda,

In order to use Mailgun, you will need to sign up with them (you can sign up for free).  Once you have signed up you will be able to view your Mailgun domain and API key.  You will need to use those in switchboard.env.

Head over to http://www.mailgun.com/ to sign up.

**Comment by rayda** [comment]
got the mailgun part sorted... but DNS approach is not working (folder based) ...I think its a problem with my DNS provider 

also does the word document approach work on specific OSs only, (what about office on mac)

**Comment by thinkst** [comment]
Glad to hear you got the Mailgun sorted.

Yes, the documents work across platforms.
