### ISSUE TITLE
Using normal SMTP Mail? (not mailgun or sendgrid)

### ISSUE THREAD

**Issue by ndom91** [thinkst/canarytokens-docker#30]
Hi All,

I've been trying for the life of me to get mails to send out via my providers normal SMTP Server on token triggers. However, the `switchboard.env` file only seems to have support for Mailgun or Sendgrid.

If possible, what are the names of the variables for the `switchboard.env` file for SMTP Server, Username, Password, etc?

Thanks!

**Comment by Zeik0s** [comment]
Yeah, this would be a nice Feature in the Future!
I think a workaround for this is a PHP form, which is hosted inside the Container or somewhere else, which get's the POST Request and then fetches the Parameter and sends the Mail.

**Comment by thinkst** [comment]
Hey @ndom91,

Currently we only support Sendgrid, Mailgun and Mandrill for Canarytokens. Ill add it to the list of things to add and we can get back to you when we have it working. 

Thanks for your interest in our project (we would love a pull request of SMTP support too 😋)

**Comment by obsti8383** [comment]
Hi @ndom91 ,
Hi @thinkst,

I have this working on my dev environment and sent a pull request in the canarytokens source repo (https://github.com/thinkst/canarytokens/pull/23).

If there are any things that need fixing or there is room for improvements don't hesitate to come back to me.

Thanks!
