### ISSUE TITLE
DNS amplification attack

### ISSUE THREAD

**Issue by robeving** [thinkst/canarytokens-docker#33]
This container is open to be used in a DNS amplification attack. This works by:

- Attacker makes a DNS request to the canary tokens server but spoofs the UDP packet with the victims IP.
- Server responds with failure message and sends this to the victim.
- Victim is deluged by traffic

The fix is to not send responses for DNS requests that are not valid

**Comment by thinkst** [comment]
Hey @robeving,

Thanks for reporting this. We are currently investigating and will get back to you soon.

**Comment by thinkst** [comment]
Hey @robeving,

Thanks again for reporting this. I have pushed a fix to the `canarytokens` repo and updated the `canarytokens-docker` images too. We haven't seen something like this happening yet, but its nice to close out the possibility (we suspect numbers would push attackers towards bigger players).

Thanks again for the reporting! We really appreciate it.
