### ISSUE TITLE
EXE/DLL generation isn't working?

### ISSUE THREAD

**Issue by kuriackovskij** [thinkst/canarytokens-docker#34]
I tried on both canarytokens.org and on my self-hosted canarytokens instance and it seems tokens embedding into exe/dll files isn't working? Whenever I try to generate a token using .exe file it returns a successful windows with green button (as usually) but button has name "Save undefined" and when clicking on it it just downloads the .html document of the actual canarytokens main page - is it a bug? Or is there any restrictions on .exe files which can be used?
Thanks.

**Comment by thinkst** [comment]
Hey @kuriackovskij,

Would you mind letting know what `.exe` you are trying to upload? I have tried a Windows 10 exe on both Canarytokens.org and my private server; and both have worked. The "Save undefined" looks like a clue because in my attempts it has shown the file name. 

If you would like to debug futher, I would suggest looking at the `sign_file.py` file in the `canarytokens` folder. In there, you will see the methods we run in order to token the exe. One method would be to attempt to run the `openssl` methods directly on your chosen `exe` in order to narrow down the point of the break.

Please let me know how this goes and we can continue to debug together.

**Comment by prashantvidja** [comment]
Hey @thinkst ,
I was trying to upload `putty.exe` file for generate EXE/DLL record but I got same `Save undefined`.
I am attaching that file Please check once.
[putty.zip](https://github.com/thinkst/canarytokens-docker/files/3193708/putty.zip)
Thanks

**Comment by thinkst** [comment]
Hey @prashantvidja,

Would you mind letting me know if this is happening on your private Canarytokens server or on Canarytokens.org? I had mentioned above in the thread that one test would be to try running the `sign_file.py` against your targeted `.exe` to determine if the signing is failing or perhaps the uploading.

**Comment by prashantvidja** [comment]
Hi @thinkst,
It is failing in my private canarytoken server.
And I think uploading is failing because i did not found any file in /uploads folder.
Thanks

**Comment by prashantvidja** [comment]
Hi @thinkst,
As per you said I have run `sign_file.py` file using targeted `.exe` file, I got succeeded message.
Please check below output for more details.

```
root@ubuntu_fresh:~/canarytokens# python sign_file.py 192.168.56.116 /root/putty.exe /root/putty.exe_org
usage: sign_file.py -t <token> -f <inputfile> -o <outputfile>
root@ubuntu_fresh:~/canarytokens# python sign_file.py -t 192.168.56.116 -f /root/putty.exe -o /root/putty_org.exe
Generating a 2048 bit RSA private key
...............+++
.....+++
writing new private key to '/tmp/tmp74yhTL/rootCA.key'
-----
Generating a 2048 bit RSA private key
..................................+++
...+++
writing new private key to '/tmp/tmp74yhTL/cert.key'
-----
Using configuration from /tmp/tmp74yhTL/root-ca.conf
Check that the request matches the signature
Signature ok
Certificate Details:
        Serial Number: 0 (0x0)
        Validity
            Not Before: Jun  4 05:24:32 2019 GMT
            Not After : Jun  3 05:24:32 2029 GMT
        Subject:
            countryName               = US
            organizationName          = Microsoft Corporation
            commonName                = Microsoft Windows
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Data Encipherment, Key Agreement
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication, Code Signing
            X509v3 Subject Key Identifier: 
                51:21:26:D5:D4:E2:AC:EF:93:D6:0C:C4:C2:41:69:89:48:AA:F9:E4
            Authority Information Access: 
                CA Issuers - URI:192.168.56.116/any_path.cer?any=params
                OCSP - URI:192.168.56.116/any_path.oscp?any=params

            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:192.168.56.116/any_path.crl?any=params

Certificate is to be certified until Jun  3 05:24:32 2029 GMT (3652 days)

Write out database with 1 new entries
Data Base Updated
Succeeded

```
Thanks

**Comment by prashantvidja** [comment]
@thinkst  solved.
There is wrong variable in `frontend.env`.
`CANARY_MAX_UPLOAD_SIZE` to `MAX_UPLOAD_SIZE` solved issue.
Thanks

**Comment by thinkst** [comment]
hey @prashantvidja,

Thats interesting. Would you mind pasting me your `frontend.env` when the upload wasn't working? Im looking at the code now and I think the upload may be working now because it is using the default rather than the value in your `.env`.

**Comment by prashantvidja** [comment]
below my `frontend.env` when it was not working.
```
CANARY_DOMAINS=mydomain.com
CANARY_NXDOMAINS=nx.mydomain.com

#CANARY_GOOGLE_API_KEY=

CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads
CANARY_MAX_UPLOAD_SIZE=1024*1024*10

LOG_FILE=frontend.log
```
CANARY_MAX_UPLOAD_SIZE to MAX_UPLOAD_SIZE solved my issue.

**Comment by jayjb** [comment]
Hey @prashantvidja,

Sorry for the delay. I checked and you are indeed correct. Although I am relatively sure that using `MAX_UPLOAD_SIZE` hasn't fixed the issue, but rather made canarytokens use the default (if the correct value isn't found in the `.env` file).

The reason your above `.env` isnt working is a failure on our side to convert `1024*1024*10` to an integer. We use the standard `int(value)` to convert `value` to an integer but when `1024*1024*10` is passed in through the `.env`, it doesn't do that multiplication but rather comes through as a string. This string then fails the above conversion. 

Thanks for reporting this. Ill change the documentation to reflect this and ticket it to be handled better.

**Comment by prashantvidja** [comment]
Thanks!
