### ISSUE TITLE
Custom Image token generation

### ISSUE THREAD

**Issue by kuriackovskij** [thinkst/canarytokens-docker#35]
Hi. Image tokens generation isn't working properly on a self-hosted instance. It generates a token which can be triggered, yes. But picture is not visible when accessing through <img src="url> tag.
Note, when using canarytokens.com - the same picture is visible so that eliminates possibility that when using self-hosted CT I am embedding picture into html page somehow wrongly. Is there anything what needs to be changed on the server side? Is there any debugging I can do and where uploaded file is being saved (to validate that upload is working correctly and picture exists) ?
Thanks.

**Comment by thinkst** [comment]
Hey @kuriackovskij,

The uploaded image is stored in a folder called `uploaded` which is created inside your `canarytokens-docker` folder. You can check that it is in there (it will be renamed but you can ensure it is the same file using a shasum check). 

Let me know if you find it or not and we can continue debugging this (I can successfully create a web image token on my private tokens server, so perhaps we are missing something with the configuration of yours)

**Comment by kuriackovskij** [comment]
Hi @thinkst,
Yes I was assuming both image files and EXE/DLL files should be uploadable to /uploads/ directory. But this directory appeared empty despite I already tried to upload files multiple times.
I did some troubleshooting including:
- set permissions to that folder (and even to all parent folders up to / ! ) to be rwx for everyone (777);
- checked docker logs and system logs for any errors, but there are no errors.
So I am thinking could it be the path or permissions hardcoded somewhere in the source code? My canarytokens-docker is located under /root/ and I am running app as root as well.
Any suggestions?

**Comment by thinkst** [comment]
Hey @kuriackovskij,

Ah thats some good digging. 

You could try checking in the actual Web Image Canarydrop. You can check this two ways:
1) exec into the redis docker, use `redis-cli` and then `hgetall` the canarydrop that is the web image. In there you will see a `web_image_path` which points to where the image is stored. Check if that points somewhere sane and check if the image is there. 
2) grep through your frontend.log for `Saved canarydrop` and check the web image canarydrop. It will show all the canarydrop details including the `web_image_path`.

Let me know how this goes. Ill check investigating to see if I can find anything else.

**Comment by kuriackovskij** [comment]
Hi @thinkst ,

Re first option, I am afraid I didn't understand how to get web_image_path. I logged in to redis container, executed `redis-cli` but then I need to provide an argument (key) for `hgetall` command otherwise it's complaining about missing argument. I am not familiar with redis so hopefully you can advise?

Re second option, frontend.log doesn't show anything about saving image or image path. Here is the sample of the log from a time when creating Image token:

> 2019-04-03 21:50:35+0000 [HTTPChannel,22,172.18.0.2] Saved canarydrop: {'browser_scanner_enabled': False, 'alert_webhook_url': '', 'timestamp': '1554328235.827249', 'memo': 'sdgsdsgsdfg', 'alert_sms_enabled': False, 'generated_url': 'http://hiddenhidden12345.com/terms/tags/traffic/xmzgnusp4g1p65bzekp9v7yk5/submit.aspx', 'alert_email_recipient': 'dsafadsfasdfhhtytyt@gmail.com', 'web_image_enabled': False, 'canarytoken': 'xmzgnusp4g1p65bzekp9v7yk5', 'auth': 'd6061326de8b0a45e2f69b56dd445b42', 'alert_webhook_enabled': False, 'type': 'web_image', 'alert_email_enabled': True, 'user': 'Anonymous'}

Any suggestions?

**Comment by thinkst** [comment]
hey @kuriackovskij,

For the first option, once you are in `redis-cli`, you will need to do `hgetall canarydrop:<canarytoken>` where `<canarytoken>` is replaced by the actual canarytoken hash. This hash can be found on the canarytoken's manage page; in the address bar as `token=`. 

Using that, you will get a bunch of information related to your canarytoken, however, by your logs, it seems that your `web_image` token is failing silently in `httpd_site.py` on token generation (this is a bug). 

In the logs you are showing me, we can see that the canarydrop does not have a `web_image_upload_path` variable and `web_image_enabled: False`. So if we go to `httpd_site.py` and check where we create this token (around line 199 we start its creation). We see that at the end of that block, if no exceptions have been raised, we would have `web_image_enabled: True`. 

So my suggestion would be to add some logging. 
`docker exec -ti frontend bash`, edit the file `httpd_site.py`.. head to line 245 and change to
`except Exception as e:`
`                log.err('Error in web_image creation: {}'.format(e))`
`                pass`

Then restart that docker container using `docker-compose restart frontend` from within `canarytokens-docker`. You can then monitor your frontend.log again and try create. Hopefully you will get a better error message.

**Comment by JonathanReifer** [comment]
Picking up where you guys left off, I edited the http_site.py file as you suggested (by adding vim to the frontend container via "apt update; apt-get install vim" ).  After restarting the container and trying to create a new web_image token I got the following error:
"Error in web_image create invalid literal for int() with base 10: '1024*1024*10'"  

Recognizing that from frontend.env and changing that from "1024*1024*10" to "10485760" (no quotes) solved the issue.  In the meantime easy fix by hand (edit frontend.env as indicated) longer term what's the "better" fix:  change the sample frontent.env to an int or change the code to handle text strings representing arithmetic?

BTW - Great project!

Lastly, is there anyway to enable more verbose logging (without having to edit the code)?

Thanks,
jonathan

**Comment by foremandrafts** [comment]
I'm having similar experience.. after running docker-compose up -d  , the uploads directory is empty, my switchboard.env and frontend.env files get zeroed out, and there are no log files. If I try running a command like docker exec -ti frontend bash  it tells me to wait until the container is running. Did they make some changes to docker since you originally built this? I know docker has been notoriously difficult to install into linux for several years. Thanks.

**Comment by foremandrafts** [comment]
I just reinstalled Ubuntu into my VPS (then updated everything) and tried the canary-docker steps again. I'm getting basically the same results. After performing docker-compose up -d   it looks like the container is starting to run correctly. Then I try a command like  docker exec -ti switchboard bash  and it tells me the container is restarting. It also continues to zero out the switchboard.env and frontend.env files right after I run the docker-compose command.. and the uploads directory continues to be empty.  I'd be happy to start another issue (rather than hijack this other person's issue), but I'm not sure if it's a problem with the package or it's just my ignorance of docker. Thanks for any help you can provide.

**Comment by thinkst** [comment]
Hey @JonathanReifer,

Thats a good find. Ill take a look at why thats happening (maybe its a simple change to the example `.env`). With regards to more verbose logging, we haven't made a setting like that simply because we log a lot of what is happening already in `frontend.log` and `switchboard.log`. Each in their respective containers.

Thanks for the kind words, and ping me if you having any other difficulties (also we love having people using this project! Hope it works for you.)

**Comment by thinkst** [comment]
hey @foremandrafts,

Im sorry that you having trouble with this. Would you mind letting me know which version of Ubuntu you are using? This way I can try replicate the issue. Also any other information you might think is useful in replicating the issue would be helpful.

**Comment by thinkst** [comment]
hey @JonathanReifer,

Would you mind removing the `CANARY_MAX_UPLOAD_SIZE` variable from your `.env` file entirely and seeing if the issue persists please?

**Comment by foremandrafts** [comment]
Hi.. thanks for your quick response. I don't have a lot of time to work with this right now. The reinstall option I'm choosing is identified as a minimal Ubuntu distro, and that's about all I know. I know there are many regular tools missing, and possibly even entire libraries. Right now it's the only Ubuntu version they offer, and their Debian distro seems a little borked. The VPS is over at sparkvps.com and I got a steep discount on a KVM container, so I didn't complain much. I'll try again when I have more time, and perhaps open a separate issue. Thanks again. R. Foreman

**Comment by foremandrafts** [comment]
Minimalist Ubuntu, but pretty recent, like version 18.04 . Everything else about it seems to run very normally, but there are a lot of missing files and folders. Anyway I don't want to drag this out. I'll get back when I have more time and start my own separate issue, you know, maybe try installing into a virtualbox on my own machine. R. Foreman

**Comment by thinkst** [comment]
Hey @foremandrafts,

I think lets start a separate issue for this one. I haven't seen this issue of the `.env` files being zeroed out before (and i am battling to replicate it too). Thanks for reporting the issue and using our project.

**Comment by jayjb** [comment]
@foremandrafts please create another issue for this. closing this issue for now.
