### ISSUE TITLE
Hidden channels and users

### ISSUE THREAD

**Issue by kuriackovskij** [thinkst/canarytokens-docker#37]
Hi,

While I was digging into the code I noticed there are some functionality (like twilio, linkedin, imgur channels, also users auth) which is hidden from web ui when using docker container. Just out of curiosity, are you planning to enable them or is it a functionality of full/paid version of canarytokens or what?
If it's available in full version, can you share a list of diffs between full and this version?
Thanks!

**Comment by thinkst** [comment]
hey @kuriackovskij,

Those channels were made more as PoCs and so we included them (talking about the LinkedIn and Imgur one). You could re-enable them if you want, but we haven't been actively using them so Im am unsure whether they will still work out of the box.

With regards to the Twilio channel, that is still available. It is a setting that you need to add to one of the config files. If you check `settings.py`, you will see the values that need to be set in order for twilio to work.

**Comment by jayjb** [comment]
Hey @kuriackovskij,

Im closing this as not an issue. If you have more queries about it, please reopen the issue and we can gladly discuss it more.
