### ISSUE TITLE
SMTP Issue

### ISSUE THREAD

**Issue by camaro23** [thinkst/canarytokens-docker#38]
Hey Guys,

I have made the below changes to the switchboard.env file but still not receiving emails via SMTP

CANARY_SMTP_SERVER=mailhost.omit.omit.omit.com
CANARY_SMTP_PORT=25
CANARY_ALERT_EMAIL_FROM_ADDRESS=canarytokens@omit.com
CANARY_ALERT_EMAIL_SUBJECT="Canary Alert via SMTP"
CANARY_SMTP_USERNAME=
CANARY_SMTP_PASSWORD=
CANARY_PUBLIC_DOMAIN=omit.omit.com
CANARY_ALERT_EMAIL_SUBJECT="Canary Token Fired"

CANARY_TOKEN_RETURN=fortune

CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads

LOG_FILE=switchboard.log

Any help would be much appreciated.

Thanks

**Comment by camaro23** [comment]
This is my full switchboard.env file by the way

**Comment by obsti8383** [comment]
Hi Camaro23,

could you try using a smtp username&password?
I think the code currently requires that.

Florian

**Comment by camaro23** [comment]
Hey @obsti8383,

Thanks for the assistance. What if I dont use authentication for this mail server? Within the container, I have ran the "mail" command to ensure that I can connect with my mail server and that works well. Do you know of any logs within the canary tokens container I could view to help troubleshoot?

Thanks

**Comment by camaro23** [comment]
Hey @obsti8383,

I found my switchboard.log file. Here is my error:

2019-04-24 10:55:10+0000 [HTTPChannel,0,172.18.0.5] "A smtp error occurred: <class 'smtplib.SMTPException'> - STARTTLS extension not supported by server."
 
Do you know what version of TLS is used by default? Can I change the version?

Thanks

**Comment by obsti8383** [comment]
Ah, that problem is independent from the password. You need an SMTP server that has STARTTLS enabled and must select the correct port (most probably 587).

Anyhow the authentication with empty password will most probably still fail, since the code tries to authenticate anyhow. I've implemented it that way, since I didn't consider the usage of anonymous SMTP relays.

**Comment by camaro23** [comment]
Hey @obsti8383,

Thanks for the quick reply. Could I point towards a postfix server and have that forward via STARTTLS?

Thanks

**Comment by obsti8383** [comment]
I don't think so (but I'm no SMTP expert). Usually TLS must terminate directly at the configured server for the client to be able to validate the certificate correctly.

I think you have to enable TLS (e.g. as described here: [http://www.postfix.org/TLS_README.html](http://www.postfix.org/TLS_README.html)) and use a certificate that is also trusted by your canarytokens/python installation.
