### ISSUE TITLE
Web UI to manage created tokens

### ISSUE THREAD

**Issue by camaro23** [thinkst/canarytokens-docker#39]
Hello,

Is there a web ui that can be used to view created tokens. I see they are stored in the data directory, but is there a way to view them through the UI?

Thanks

**Comment by thinkst** [comment]
Hey @camaro23,

There is a basic web ui used to view each individual Canarytoken you create. 

The manage page link for each canarytoken will be sent in the email alert you receive, but the manage links follow https://yourcanarytokendomain.com/manage?token=<canarytoken_hash>&auth=<auth_code>.

You can manually find these values by jumping into your redis docker container using `docker exec -ti redis redsi-cli` and doing a `keys canarydrop:*` to view all your saved canarytokens. These entries are hsets so you can view their details by `hget canarydrop:<canary_hash>` (the auth value will be in that hset of the canarytoken too).

**Comment by camaro23** [comment]
Hey @thinkst,

Thank you for the quick response. I will run those commands and view my output. I will provide a follow up shortly.

Thanks
