### ISSUE TITLE
JSON Output

### ISSUE THREAD

**Issue by camaro23** [thinkst/canarytokens-docker#40]
Hey Thinkst Team,

Is there a way to convert the switchboard.log file into a JSON output? I am having to perform a work around due to no STARTTLS capability and I am looking to implement the swithboard.log file into my SIEM to receive real time alerts when a token is fired. However, I am having difficulty decoding the swithboard.log file into a format my SIEM tool can read. Any suggestions would be greatly appreciated!

Thanks for the help

**Comment by thinkst** [comment]
Hey @camaro23, 

We dont have a neat way to convert `switchboard.log` into JSON however if you are integrating your OpenCanary with your SIEM, then I suspect you would only want to see incident information coming through (rather then all the debug/operational info that is output into `switchboard.log`.

I would suggest taking a look at the other logging options over [here](http://docs.opencanary.org/en/latest/starting/configuration.html). With SIEM integration, we have seen people use the syslog or the tcp-json logger. 

If the normal use case loggers don't work for you, we also have another project that runs with OpenCanary, known as OpenCanary Correlator which collects events and correlates them which can be useful for sending through to a SIEM.

Let me know if this helps or if you need any more information.

**Comment by jayjb** [comment]
Hey @camaro23,

Let me know if you got everything sorted or if there is some more advice you may need.

**Comment by camaro23** [comment]
Hey @ghost and @jayjb,

Apologies for the late reply. I have figured a work around solution that works for my environment. Thank you both for your suggestions!
