### ISSUE TITLE
Baisc Auth is preventing tokens from triggering

### ISSUE THREAD

**Issue by mamisano** [thinkst/canarytokens-docker#42]
The current instructions call for placing the auth_basic settings under `server` which requires auth for all traffic to the server, including triggering a token. This is preventing any tokens from triggering and notifying owners.

The auth_basic settings should be moved under the `location` declaration for generate, manage, download, history, settings and resources. Those are the locations that should be secured via auth.

Current:

> server {
    auth_basic           "Basic Auth Restricted Canrytokens"; <---- ADD
    auth_basic_user_file /etc/nginx/htpasswd;                 <---- ADD

Proposed:
>location ~* (/generate|/manage|/download|/history|/settings|/resources).* {
            auth_basic           "Basic Auth Restricted Canrytokens";
            auth_basic_user_file /etc/nginx/.htpasswd;

**Comment by jayjb** [comment]
Hey @mamisano,

Thanks so much for spotting this. It was such a silly issue and I hope it hasn't affected anyone. Ive made changes to the documentation.
