### ISSUE TITLE
Canary Tokens custom domain Windows Folder not working

### ISSUE THREAD

**Issue by NickKoz2210** [thinkst/canarytokens-docker#43]
I am having trouble with the use of my windows folder token on my custom server.  I have connected two different domains, one for the http traffic and one for the DNS channel traffic as it said in GIT hub.  I believe i am pointing my DNS domain to the canary token instance, but it doesnt seem to be working. 

@jayjb @stevesbrain @obsti8383 @mamisano

**Comment by NickKoz2210** [comment]
@jayjb

**Comment by jayjb** [comment]
Hey @NickKoz2210,

Sorry for the delay. Would mind telling me if your DNS token works? and if your HTTP token works? The Windows Folder token is, at heart, a DNS token. 

So if your regular DNS token is working, then it may point to the actual machine on which you are opening the Windows Folder. If this is the case, please ensure the Windows Folder has the system attribute.

Lastly, if the above hasnt worked. You can view hidden files inside the Windows Folder and open the `desktop.ini`. Inside there, you will see an address which is the token. If you copy the address (something like `XXXXX.your.token.server.com`), open your Windows Powershell and try `nslookup <copied_address>`. 

You should get an alert or see that query hitting your canarytokens DNS server. Please let me know how it goes.

**Comment by jayjb** [comment]
Haven't heard back from @NickKoz2210. Closing the issue for now.
