### ISSUE TITLE
Guide to installation without the docker ? 

### ISSUE THREAD

**Issue by keldnorman** [thinkst/canarytokens-docker#45]
Does a guide for installing the framework without using docker exist ? I would like to have a native installation.

Best regards
Keld Norman

**Comment by jayjb** [comment]
Hey @keldnorman,

We dont have a guide to installing it without docker unfortunately. We figured that the docker approach would be the easiest plug and play for folks. 

If you still interested in running Canarytokens natively, you could follow the `docker-compose.yml` file as a sort of guide to getting it up and running. If you choose to pursue this, feel free to ping me and we can come up with a guide together (step by step!).

**Comment by jayjb** [comment]
Closing this issue because we dont recommend running the Canarytokens Server without docker. I have however mentioned an approach one might take in the [Canarytokens Wiki](https://github.com/thinkst/canarytokens/wiki).
