### ISSUE TITLE
How to enable HTTP to redirect automatically to HTTPS?

### ISSUE THREAD

**Issue by repogh** [thinkst/canarytokens-docker#46]
I have letsencrypt and everything works, but you have to manually change http to https, how can I enable auto redirect to https please?

**Comment by jayjb** [comment]
Hey @mradsgh,

Thanks for reporting this. I totally thought we were doing it already. Ill take a look and once I get it working, ill ping you with some steps. Alternatively, if you get it going before, we would appreciate a PR with some steps to getting it going.

**Comment by jaswinder97** [comment]
@jayjb let me know where we are with this feature

**Comment by jayjb** [comment]
Hey @mradsgh, @jaswinder97,

I wanted to check something about this ticket (because it varies in dev work). Are you asking for Canarytokens frontend to always be served as HTTPS or the actual canarytokens trigger urls to be in HTTPS?

**Comment by mradsgh** [comment]
Yes, the frontend to always be served as HTTPS, I still havent been able to get it to work, but I have limited experience with docker and nginx.

If I get it to work before anyone else, ill post it.

**Comment by jaswinder97** [comment]
@mradsgh @jayjb  I was able to run HTTPS as frontend with latest master and with some minor tweaks for nginx container configs

`events { worker_connections 1024; }
http {
        server {
                client_max_body_size 50M;
                listen 80;
                server_name myexample.com www.myexample.com ;
                return 301 https://$server_name$request_uri;

        }

        server {
                
                server_name myexample.com www.myexample.com ;

                sendfile on;
                gzip              on;
                gzip_http_version 1.0;
                gzip_proxied      any;
                gzip_min_length   500;
                gzip_disable      "MSIE [1-6]\.";
                gzip_types        text/plain text/xml text/css
                                text/comma-separated-values
                                text/javascript
                                application/x-javascript
                                application/atom+xml;

                default_type  application/octet-stream;
                include       /etc/nginx/mime.types;
		        server_tokens off;
        		location ^~ /.well-known/acme-challenge {
                                proxy_pass http://nginx:80;
                                proxy_set_header Host            $host;
                                proxy_set_header X-Forwarded-For $remote_addr;
                                proxy_set_header X-Forwarded-Proto https;
                        }

        		location = / {
                    proxy_pass         http://frontend:8082/;
                    proxy_redirect     off;
                    proxy_set_header   Host $host;
                    proxy_set_header   X-Real-IP $remote_addr;
                    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header   X-Forwarded-Host $server_name;
                }
                location ~* (/generate|/manage|/download|/history|/settings|/resources).* {
                    proxy_pass         http://frontend:8082;
                    proxy_redirect     off;
                    proxy_set_header   Host $host;
                    proxy_set_header   X-Real-IP $remote_addr;
                    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header   X-Forwarded-Host $server_name;
                }
                location = /robots.txt {
                    proxy_pass         http://frontend:8082/robots.txt;
                    proxy_redirect     off;
                    proxy_set_header   Host $host;
                    proxy_set_header   X-Real-IP $remote_addr;
                    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header   X-Forwarded-Host $server_name;
                }
                location ~ [.]* {
                    proxy_pass         http://switchboard:8083;
                    proxy_redirect     off;
                    proxy_set_header   Host $host;
                    proxy_set_header   X-Real-IP $remote_addr;
                    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header   X-Forwarded-Host $server_name;
                }

        
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/myexample.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/myexample.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
  }
}`


@mradsgh you can just edit the nginx.conf file similar to the above in nginx container at path `/etc/nginx/nginx.conf` and restart it. It should work as expected

**Comment by mradsgh** [comment]
> 
> 
> @mradsgh @jayjb I was able to run HTTPS as frontend with latest master and with some minor tweaks for nginx container configs
> 
> ```
> events { worker_connections 1024; }
> http {
>         server {
>                 client_max_body_size 50M;
>                 listen 80;
>                 server_name myexample.com www.myexample.com ;
>                 return 301 https://$server_name$request_uri;
> 
>         }
> 
>         server {
>                 
>                 server_name myexample.com www.myexample.com ;
> 
>                 sendfile on;
>                 gzip              on;
>                 gzip_http_version 1.0;
>                 gzip_proxied      any;
>                 gzip_min_length   500;
>                 gzip_disable      "MSIE [1-6]\.";
>                 gzip_types        text/plain text/xml text/css
>                                 text/comma-separated-values
>                                 text/javascript
>                                 application/x-javascript
>                                 application/atom+xml;
> 
>                 default_type  application/octet-stream;
>                 include       /etc/nginx/mime.types;
> 		        server_tokens off;
>         		location ^~ /.well-known/acme-challenge {
>                                 proxy_pass http://nginx:80;
>                                 proxy_set_header Host            $host;
>                                 proxy_set_header X-Forwarded-For $remote_addr;
>                                 proxy_set_header X-Forwarded-Proto https;
>                         }
> 
>         		location = / {
>                     proxy_pass         http://frontend:8082/;
>                     proxy_redirect     off;
>                     proxy_set_header   Host $host;
>                     proxy_set_header   X-Real-IP $remote_addr;
>                     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>                     proxy_set_header   X-Forwarded-Host $server_name;
>                 }
>                 location ~* (/generate|/manage|/download|/history|/settings|/resources).* {
>                     proxy_pass         http://frontend:8082;
>                     proxy_redirect     off;
>                     proxy_set_header   Host $host;
>                     proxy_set_header   X-Real-IP $remote_addr;
>                     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>                     proxy_set_header   X-Forwarded-Host $server_name;
>                 }
>                 location = /robots.txt {
>                     proxy_pass         http://frontend:8082/robots.txt;
>                     proxy_redirect     off;
>                     proxy_set_header   Host $host;
>                     proxy_set_header   X-Real-IP $remote_addr;
>                     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>                     proxy_set_header   X-Forwarded-Host $server_name;
>                 }
>                 location ~ [.]* {
>                     proxy_pass         http://switchboard:8083;
>                     proxy_redirect     off;
>                     proxy_set_header   Host $host;
>                     proxy_set_header   X-Real-IP $remote_addr;
>                     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>                     proxy_set_header   X-Forwarded-Host $server_name;
>                 }
> 
>         
>     listen 443 ssl; # managed by Certbot
>     ssl_certificate /etc/letsencrypt/live/myexample.com/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/myexample.com/privkey.pem; # managed by Certbot
>     include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
>   }
> }
> ```
> 
> @mradsgh you can just edit the nginx.conf file similar to the above in nginx container at path `/etc/nginx/nginx.conf` and restart it. It should work as expected

Does this redirect anyone who puts in http://website.com to httpS://website.com ?

**Comment by jayjb** [comment]
Im closing this ticket because I think there is going to be issue with HSTS essentially. We dont want to force connections to `example.com` to upgrade to HTTPS because our tokens will be using the same `example.com/token/img.jpg` and we do not want to force Canarytoken connections to upgrade to HTTPS (we have discussed this internally).

The option here would be have to two separate domains, one for frontend and one for canarytoken connections. The frontend, `example.com` could be setup to upgrade connections, while the canarytoken connection domain, `example2.com` could be setup to not worry. This would require some changes on the nginx config side to route requests for different domains to different backend services (`frontend` or `switchboard`).
