### ISSUE TITLE
Imgur error: string indices must be integers, not str

### ISSUE THREAD

**Issue by jaswinder97** [thinkst/canarytokens-docker#48]
Getting an error with let's encrypt docker compose 

`switchboard    | 2019-09-10 05:44:27+0000 [-] Starting factory <channel_input_smtp.CanarySMTPFactory object at 0x7f23297bd990>
switchboard    | 2019-09-10 05:44:28+0000 [-] 'Imgur error: string indices must be integers, not str'
nginx          | Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
`

**Comment by jaswinder97** [comment]
@jayjb could you please look into this for once

**Comment by jayjb** [comment]
Hi @jaswinder97,

Im sorry you having this issue. I will take a look and get back to you.

**Comment by jayjb** [comment]
Hi @jaswinder97,

Ive just done some tests with some working SMTP settings and didn't hit that issue. Would you mind pasting me a copy of your `.env` files so I can try replicate the issue?

**Comment by jaswinder97** [comment]
Hi @jayjb 

This was the last conflict for:
```
Conflicts:
    	canarytokens/Dockerfile
    	docker-compose.yml
    	frontend.env
    	switchboard.env
```
**1. canarytokens/Dockerfile**

   `FROM ubuntu:16.04
MAINTAINER Marco Slaviero <marco@thinkst.com>
LABEL Description="This image provides the frontend site for Canarytokens" Vendor="Thinkst Applied Research" Version="1.4"
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates wget python-pip unzip osslsigncode gcc python-dev libreadline-dev libncurses5-dev libffi-dev gcc patch make libxslt-dev libxml2-dev libz-dev fortune-mod fortunes libssl-dev && rm -rf /var/lib/apt/lists/*
WORKDIR /
RUN pip install -U setuptools
RUN pip install --upgrade pip
RUN pip install --no-cache-dir pyOpenSSL==16.2.0
RUN pip install --no-cache-dir Jinja2==2.9.4
RUN pip install --no-cache-dir MarkupSafe==0.23
RUN pip install --no-cache-dir Twisted==15.2.1
RUN pip install --no-cache-dir cssselect==0.9.1
RUN pip install --no-cache-dir docopt==0.4.0
RUN pip install --no-cache-dir gnureadline==6.3.3
RUN pip install --no-cache-dir httplib2==0.9.1
RUN pip install --no-cache-dir lxml==3.4.4
RUN pip install --no-cache-dir mandrill==1.0.57
RUN pip install --no-cache-dir pytz==2015.4
RUN pip install --no-cache-dir redis==2.10.3
RUN pip install --no-cache-dir requests==2.20.0
RUN pip install --no-cache-dir simplejson==3.7.3
RUN pip install --no-cache-dir six==1.10.0
RUN pip install --no-cache-dir twilio==4.4.0
RUN pip install --no-cache-dir twill==1.8.0
RUN pip install --no-cache-dir wsgiref==0.1.2
RUN pip install --no-cache-dir zope.interface==4.1.2
RUN pip install --no-cache-dir PyQRCode==1.2.1
RUN pip install --no-cache-dir pypng==0.0.18
RUN pip install --no-cache-dir lockfile==0.12.2
RUN pip install --no-cache-dir python-daemon==2.1.1
RUN pip install --no-cache-dir pyzmq==15.4.0
RUN pip install --no-cache-dir htmlmin==0.1.10
RUN pip install --no-cache-dir sendgrid==3.6.5
RUN pip install --no-cache-dir service_identity

RUN wget -O master.tar.gz --header='Authorization: token **abcsefghijk**' https://api.github.com/repos/nathanhouse/stationx-canary-tokens/tarball

RUN mkdir stationx-canary-tokens

RUN tar -zxvf master.tar.gz -C stationx-canary-tokens --strip-components=1

RUN mv /stationx-canary-tokens/* /srv

RUN rm -rf /stationx-canary-tokens

WORKDIR /srv

COPY settings.ini /srv/subscribe-daemon/settings.ini

CMD echo "Please use the docker-compose setup described at https://github.com/thinkst/canarytokens-docker"
`
Note: In above file we are using canarytokens from another repo which hasn't been changed since last two years. 
`https://api.github.com/repos/nathanhouse/stationx-canary-tokens/tarball`

**2.docker-compose.yml** (but we are using let's encrypt), So the content below is for `docker-compose-letsencrypt.yml`

`version: '2'
services:
  redis:
    restart: always
    image: redis
    volumes:
    - ./data:/data/
    container_name: redis
    command: redis-server --appendonly yes --protected-mode no --save 60 1
  frontend:
    restart: always
    build: ./canarytokens/
    image: thinkst/canarytokens
    links:
     - redis
    env_file:
     - frontend.env
    volumes:
    - ./uploads:/uploads/
    - log-volume:/logs
    container_name: frontend
    command: bash -c "rm subscribe-daemon/subscribe-daemon.pid; python subscribe-daemon/subscribe-d.py start & rm frontend.pid; twistd -noy frontend.tac -l frontend.log --pidfile=frontend.pid"
  switchboard:
    build: ./canarytokens/
    restart: always
    image: thinkst/canarytokens
    ports:
     - "53:53"
     - "53:53/udp"
     - "25:25"
    links:
     - redis
    env_file:
     - switchboard.env
    volumes_from:
    - frontend
    container_name: switchboard
    command: bash -c "rm switchboard.pid; twistd -noy switchboard.tac --logger log.logger --pidfile=switchboard.pid"
  nginx:
    restart: always
    image: thinkst/certbot-nginx
    build: ./certbot-nginx/
    ports:
     - "80:80"
     - "443:443"
    links:
     - frontend
     - switchboard
    container_name: nginx
    env_file:
     - certbot.env
volumes:
  log-volume:
      
`
**3. frontend.env**

`CANARY_DOMAINS=magicclouddrive.com
CANARY_NXDOMAINS=magicclouddrive.com

#CANARY_GOOGLE_API_KEY=

CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads

#Enter number so 1024*1024*10 = 10485760
CANARY_MAX_UPLOAD_SIZE=10485760

LOG_FILE=frontend.log`

**4.switchboard.env**

`CANARY_MAILGUN_DOMAIN_NAME=whiteclouddrive.com
#CANARY_MAILGUN_API_KEY=
#CANARY_MANDRILL_API_KEY=
#CANARY_SENDGRID_API_KEY=
CANARY_PUBLIC_IP=52.35.180.52
CANARY_PUBLIC_DOMAIN=magicclouddrive.com
CANARY_ALERT_EMAIL_FROM_ADDRESS=jaswindersinghsn97@gmail.com
CANARY_ALERT_EMAIL_FROM_DISPLAY="StationX Canarytokens"
CANARY_ALERT_EMAIL_SUBJECT="ALERT - StationX Canarytoken Triggered"
#CANARY_IPINFO_API_KEY=

CANARY_TOKEN_RETURN=fortune

CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads

LOG_FILE=switchboard.log
`
I think these would help but incase you need to know anything just ask

**Comment by jayjb** [comment]
Hi @jaswinder97,

Thank you for sending through the above details. Reading through them I can see that you are trying to use a different repo of canarytokens (namely stationx's version). Unfortunately, I do not know what changes they have made so I can't look into this issue further

**Comment by jaswinder97** [comment]
@jayjb jus ignore that because it was working with the same code earlier. Just focus on these conflict changes or with the latest release of letsencrypt

**Comment by jayjb** [comment]
Hi @jaswinder97,

The conflict changes come from having edited files in your repo when git is trying to pull. I think you have those files populated with details whereas the `master` branch has them as empty. You can move the `.env` files out so long to remove that conflict. 

The other conflict, in the `Dockerfile` is the many changes to pull the stationx's repo instead of ours. Please note that in those changes, namely, 
`RUN wget -O master.tar.gz --header='Authorization: token abcsefghijk' https://api.github.com/repos/nathanhouse/stationx-canary-tokens/tarball`
it looks like you may have made your auth token publicly viewable. We suggest rotating that auth token as soon as possible please (we are not sure what privileges it has). 

Lastly, I want to mention that I have created a new canarytokens server using the current repo (and didnt hit these issues). Would you mind trying creating a clean one from our repo and see if you hit the same issues?

**Comment by jaswinder97** [comment]
@jayjb sure checking directly with your repo

**Comment by jaswinder97** [comment]
@jayjb could you please email me some logs of `switchboard` container. just wanted to confirm because I am still facing issues with latest code

**Comment by jayjb** [comment]
Hey @jaswinder97,

Sorry about the delay..  I was looking at the error you hitting and I searched through our repo. It seems you would only hit that error if you are trying to use Imgur. Is this the case? We haven't used that part of the code in a while and so I would need to recheck and ensure that it is still working.

**Comment by jayjb** [comment]
Closing this issue because I haven't heard back.
