### ISSUE TITLE
On restart, nginx gets stuck restarting

### ISSUE THREAD

**Issue by BeanBagKing** [thinkst/canarytokens-docker#5]
When I reboot my VPS, the docker images attempt to restart. Redis and grontend do so without a problem, then nginx gets stuck in a restarting loop. According to the yml, switchboard isn't set to restart at all (the others are set to restart always).

I'm fairly new to docker containers, so I'm not sure if this is something I've done wrong, or incorrect behavior. If there are any logs I can provide, please let me know what is needed and from where.

**Comment by thinkst** [comment]
We have added the restart to all the services.
