### ISSUE TITLE
'frontend' failed to build

### ISSUE THREAD

**Issue by repogh** [thinkst/canarytokens-docker#52]
Ive been using this repo for at least a year and been about to build a new webserver from it on Linux (ubuntu 18.04), however I have just tried this weekend and now get the following error during sudo docker-compose build:

Step 11/37 : RUN pip install --no-cache-dir Twisted==15.2.1
 ---> Running in 642adaac9a7c
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting Twisted==15.2.1
  Downloading https://files.pythonhosted.org/packages/ce/1b/1563ef82c2103ee937a78800486812da511e31e51b70870183ba82123a7c/Twisted-15.2.1.tar.bz2 (4.6MB)
Collecting zope.interface>=3.6.0
  Downloading https://files.pythonhosted.org/packages/d3/f0/521019b86fadc15272fd1229fbad811c4af5ad8f63a2ec604e0b50e7b473/zope.interface-4.7.1-cp27-cp27mu-manylinux2010_x86_64.whl (164kB)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from zope.interface>=3.6.0->Twisted==15.2.1) (45.0.0)

ERROR: Package 'setuptools' requires a different Python: 2.7.12 not in '>=3.5'
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c pip install --no-cache-dir Twisted==15.2.1' returned a non-zero code: 1

I have tried to google but im a novice on this, maybe you are aware of the issue already?

I never make any changes but seems some dependence have changed

**Comment by jonpwilson** [comment]
We had the same issue but managed to fix it by changing https://github.com/thinkst/canarytokens-docker/blob/master/canarytokens/Dockerfile#L1 from "ubuntu:16:04' to "ubuntu:18:04" and running docker-compose. 

Not sure if this is going to break anything else, but so far it's up and running

**Comment by repogh** [comment]
> 
> 
> We had the same issue but managed to fix it by changing https://github.com/thinkst/canarytokens-docker/blob/master/canarytokens/Dockerfile#L1 from "ubuntu:16:04' to "ubuntu:18:04" and running docker-compose.
> 
> Not sure if this is going to break anything else, but so far it's up and running

Yeah I tired that too but for some reason I also had to change line 16 to:
RUN pip install --no-cache-dir lxml

As version 3.4.4 was erroring for me and I didnt wanna spend time figuring out the version needed.

**Comment by jayjb** [comment]
Hi @repogh,

Im sorry about that issue. Let me make some changes so that it starts up reliably. If the fix is to simply change to new ubuntu, thats great (thanks @jonpwilson!). Sorry im delayed in responding.

**Comment by jaswinder97** [comment]
@repogh I think updating the base image will break DNS tokens triggers. Could you please confirm whether the DNS tokens are working for your system or not

**Comment by jaswinder97** [comment]
@jonpwilson does DNS tokens working with the base image updates for you?

**Comment by jayjb** [comment]
Hi @jaswinder97,

The canarytokens.org site is running the latest docker images. The latest docker images include an upgraded base image to 18.04.

**Comment by jayjb** [comment]
Closing this issue. We have successfully updated to ubuntu 18.04.
