### ISSUE TITLE
Email server settings?

### ISSUE THREAD

**Issue by Blason** [thinkst/canarytokens-docker#53]
Hi Folks,

Not sure if I have missed, but how do I set up custom email server settings to send a mail from? If I don't want to use default API settings fro mailgun and instead would like to use my internal email server, where do I define that?

TIA 
Blason R

**Comment by Blason** [comment]
I am still not getting it folks, can someone pls point me to the documents where those settings are mentioned?

**Comment by jayjb** [comment]
Hi @Blason,

Sorry for the delayed response. If you check out [canarytokens](https://github.com/thinkst/canarytokens), there is a section about configuring SMTP at the bottom of the page. 

Let me know if this helps otherwise I can try explain further.

**Comment by Blason** [comment]
Awesome man thanks. Dont know how did I miss that?
