### ISSUE TITLE
can't get the master.zip file

### ISSUE THREAD

**Issue by qingweiqm** [thinkst/canarytokens-docker#6]
when running the docker-compose up, it hangs with below info:

--2016-06-21 07:29:59--  https://github.com/thinkst/canarytokens/archive/master.zip?step=1
Resolving github.com (github.com)... 192.30.252.128
Connecting to github.com (github.com)|192.30.252.128|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/thinkst/canarytokens/zip/master [following]
--2016-06-21 07:30:01--  https://codeload.github.com/thinkst/canarytokens/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.

I can download the file with the command in Dockerfile "wget -O master.zip https://github.com/thinkst/canarytokens/archive/master.zi
p?step=1", but it just hang on there.

Any suggestions?

**Comment by qingweiqm** [comment]
--2016-06-21 07:57:57--  https://github.com/qingweiqm/canarytokens-docker/archive/master.zip
Resolving github.com (github.com)... 192.30.252.120
Connecting to github.com (github.com)|192.30.252.120|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/qingweiqm/canarytokens-docker/zip/master [following]
--2016-06-21 07:57:59--  https://codeload.github.com/qingweiqm/canarytokens-docker/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
Unable to establish SSL connection.
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c wget -O master.zip https://github.com/qingweiqm/canarytokens-docker/archive/master.zip' returned a non-zero code: 4

**Comment by qingweiqm** [comment]
I try to change the url to my github account, but still fails.

**Comment by thinkst** [comment]
Tried to check if this issue persists. Haven't heard back. Closing issue.
