### ISSUE TITLE
Can't generate AWS token

### ISSUE THREAD

**Issue by adrienpessu** [thinkst/canarytokens-docker#61]
Hello everyone,

Thank you for the awesome work with Canary token.
I manage to install this docker version on an AWS EC2 instance and the SMTP configuration works fine.
I can generate a custom image or fast redirect and it works, but when I try to generate AWS keys, I get stuck in the inactive form and the credentials layer doesn't show. 
I get no relevant logs from `docker-compose logs` and the only I get is in return from HTTP get call to /generate, I get : 
Error_Message: "Failed to retrieve AWS API keys. Please contact support@thinkst.com."

I won't contact `support@thinkst.com` because I don't pay for thinkst services. 

How could I get more logs about this situation?
Thanks a lot in advance.

Adrien

**Comment by jayjb** [comment]
Hi @adrienpessu,

Thanks for giving it a spin and I hope we can get it up and running for you as soon as possible.

In terms of checking some logs; a useful way will be to get into the docker container (say `switchboard`), and check the `switchboard.log` in there. You can do this by:
`docker exec -ti switchboard /bin/bash` which will take you into the container, and then maybe tailing the `switchboard.log` using `tail -f switchboard.log`. Go to your browser, try generate an AWS API Key Canarytoken and see what those logs say. 

In trying to get this sorted, would you mind telling me a little more about your setup? 

Let me know,
Jay

**Comment by adrienpessu** [comment]
Hello @jayjb ,

I have checked that `switchboard.log` without any luck. It seems that in the output of the command `docker-compose logs`, we can find the content of the `switchboard.log` file.

About my setup, I have created a EC2 instance from AMI linux 2. I have installed docker and docker-compose. I have checkout the repository canarytokens-docker.

My `switchboard.env` looks like this : 
```
CANARY_PUBLIC_IP=66.66.66.66
CANARY_PUBLIC_DOMAIN=ec2-66.66.66.66.eu-west-1.compute.amazonaws.com

CANARY_ALERT_EMAIL_FROM_ADDRESS=me@email.com
CANARY_ALERT_EMAIL_FROM_DISPLAY="Security"
CANARY_ALERT_EMAIL_SUBJECT="[SECURITY] honeypot"
CANARY_SMTP_SERVER=smtp.server
CANARY_SMTP_PORT=587
CANARY_SMTP_USERNAME=me@email.com
CANARY_SMTP_PASSWORD=changeme
CANARY_TOKEN_RETURN=fortune
CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads
LOG_FILE=switchboard.log
```

and my `frontend.env` looks like this : 

```
CANARY_DOMAINS=ec2-66.66.66.66.eu-west-1.compute.amazonaws.com
CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads
CANARY_MAX_UPLOAD_SIZE=10485760
LOG_FILE=frontend.log
```

Thank you so much for your help,

Best regards,

Adrien

**Comment by jayjb** [comment]
Hi @adrienpessu,

Thanks for getting back to me so fast; ah thats useful to note about the logs, thank you. 

So the next step, I think, would be to see if you can hit the AWS API Key Canarytoken endpoint from that server. So once you are ssh'ed into `ec2-66.66.66.66.eu-west-1.compute.amazonaws.com` (assuming thats a fake address); you could try pinging or curling the endpoint to see that your server has access. 

Something like:
`curl -kis "https://1luncdvp6l.execute-api.us-east-2.amazonaws.com/prod/CreateUserAPITokens"` just to check that you can hit it.

Let me know how it goes.

Kind regards,
Jay

**Comment by adrienpessu** [comment]
@jayjb 

From my well named server `ec2-66.66.66.66.eu-west-1.compute.amazonaws.com`, 

I get : 

```
curl -kis "https://1luncdvp6l.execute-api.us-east-2.amazonaws.com/prod/CreateUserAPITokens"
HTTP/2 502
content-type: application/json
content-length: 36
date: Wed, 25 Mar 2020 13:34:46 GMT
x-amzn-requestid: 0835b7a4-4614-42d5-a2dc-319868b6446c
x-amzn-errortype: InternalServerErrorException
x-amz-apigw-id: J8uecEvhCYcFkyA=
x-cache: Error from cloudfront
via: 1.1 003bc9225f430357abb8eb4b34f6dc20.cloudfront.net (CloudFront)
x-amz-cf-pop: DUB2-C1
x-amz-cf-id: KNEIfYEPvBzZdyLUD5_HHm9TokftFNBzBurPY0kX3FWuZfN0vIXgFw==

{"message": "Internal server error"}
```

I get the same result if I put the url `https://1luncdvp6l.execute-api.us-east-2.amazonaws.com/prod/CreateUserAPITokens` in my browser.

Best regards,

Adrien

**Comment by jayjb** [comment]
@adrienpessu, 

Thanks for testing that. Just trying to cancel out places that may be the issue (also thanks for the output, I saw that request hit the endpoint and have made some changes to return a more useful message). 

So looking through the code a bit, I see we have a limit on the domain name size (when trying AWS API Key Canarytoken. Since we append the domain name and the canarytoken together, your domain name size can be a maximum of 39 characters (which would mean your example domain above would not be accepted).

I notice that this isn't clear anywhere; so ill add it to the documentation for future use. Let me know if that makes sense.

Kind regards,
Jay

**Comment by adrienpessu** [comment]
Thank you very much for your help.

I will try to get a hand on a shorter domain name, I will get back to you shortly to inform you of the success.

Have a nice day,

Adrien

**Comment by adrienpessu** [comment]
Hello again,

With a shorter domain name, I was able to generate AWS credentials. 
Thank you a lot.

But when I test it, I don't get the email.
To test, I do `aws s3 ls --profile honey`
I have a [honey] profile in my credentials file with the all the information generated by the canary token.

Did I miss something in the configuration? 

Best regards,

Adrien

**Comment by jayjb** [comment]
Hi @adrienpessu,

Thanks for getting back to me with more info. So i have checked the logs and see both your created canarytokens and the triggering of them. The issue here is that the triggering mechanism relies on triggering a DNS canarytoken. 

Would you mind ensuring that DNS Canarytokens are working on your new setup please?

In terms of getting the DNS working correctly; you will need to add more than just a A record. If your public IP is 1.2.3.4 and your canarytokens domain is ns.test.com, you would generally need something like this:
test.com A 1.2.3.4
ns.test.com. NS test.com
pdf.test.com NS test.com

Using the above, you could use the `pdf.test.com` as your NX domain.

Please let me know if this works out.

**Comment by adrienpessu** [comment]
@jayjb 

I changed my DNS records, and it takes a few minutes to propagate.
To be closer to your last message, I use a domain instead of a subdomain
I guess you could see it in your logs.
But, it still doesn't work with AWS token. I have checked, it still works with "slow redirect"

I feel I am close to success. 
If you think it is a good idea, I could make a PR to enrich the `readme.md` file, to avoid people falling into the same mistakes I made. (Or at least a medium post with a step by step)

**Comment by jayjb** [comment]
@adrienpessu,

ah awesome, lets see how that goes with the updated DNS records.

With regards to the "slow redirect", is that it is an HTTP token. The AWS API Key Canarytoken uses the DNS channel; which can be test by creating a DNS Canarytoken and running:
`host <canarytoken>.<your domain>` 
So as an example, I created a DNS Canarytoken on canarytokens.org and copied the Canarytoken. I can trigger it by:
` host hx332u91x6gdf7eaqhmzpnx6q.canarytokens.com`

This is the same channel of beaconing/alerting that the AWS API key Canarytoken uses.

Haha, I feel like you are very close to success too. Keep at it! We'll get it working soon. I think either (or both would be great). I can help you with either of those if you need any input.

**Comment by adrienpessu** [comment]
@jayjb 

I guess the DNS is updated. 
I tried : 
```
host 8xqxlets30dgqtgn4r4l3bf5w.test.com
8xqxlets30dgqtgn4r4l3bf5w.test.com has address 66.66.66.66
```
I didn't get the email. 
I also tried to generate a DNS token on canarytokens.com and there, it's work.

I don't know what I am missing. 🤔

**Comment by jayjb** [comment]
@adrienpessu,

Just to be clear; so that i have a clear picture in my mind. 

You did the following steps:
1) created a DNS Canarytoken (`8xqxlets30dgqtgn4r4l3bf5w`) on test.com. 
2) run `host 8xqxlets30dgqtgn4r4l3bf5w.test.com` and got the response `8xqxlets30dgqtgn4r4l3bf5w.test.com has address 66.66.66.66`.
3) didn't receive an email or notification that the Canarytoken triggered?

But when you created a DNS Canarytoken on canarytokens.org, and triggered it, it worked?

**Comment by adrienpessu** [comment]
Yes, this exactly that. 
(Sorry, my previous message wasn't clear)

**Comment by jayjb** [comment]
@adrienpessu,

Sorry for the delay. So i think the steps forward now to determine where the break is:
a) not receiving the DNS request on your Canarytokens server? (Try triggering the DNS Canarytoken and tailing the switchboard.log to ensure the request is hitting your server)
b) if receiving, does the triggered DNS Canarytoken show up in the "Manage this Token" screen. (So once you create the DNS Canarytoken, you will notice a "Manage" link in the top right; after we confirm the DNS request is hitting the server, lets see if the Canarytoken is getting triggered?)
c) if it is being triggered (i.e. showing up in that "Manage" screen), then lets log into our mail server and check whether the mail is reaching there or getting further? (also check your Spam folder, ive been fooled by that a couple times recently)

Please let me know how these steps go.

**Comment by adrienpessu** [comment]
@jayjb 

It's a, there is nothing new in `switchboard.log` when I trigger DNS request `host 8xqxlets30dgqtgn4r4l3bf5w.test.com`

**Comment by jayjb** [comment]
@adrienpessu, 

I thinking it may be a DNS issue then. Could paste your DNS zone file here? (obfuscating info as necessary). We should be seeing any DNS queries for test.com coming through to your test.com Canarytokens server. Please make sure that your test.com server is the authoritative DNS server for test.com.

**Comment by adrienpessu** [comment]
Sure, I am not 100% confident in my DNS zone file, to it can be it : 
```
@ 10800 IN SOA ns1.provider.net. hostmaster.provider.net. 1585574538 10800 3600 604800 10800
* 10800 IN A 66.66.66.66
@ 10800 IN A 66.66.66.66
@ 10800 IN MX 10 spool.mail.provider.net.
@ 10800 IN MX 50 fb.mail.provider.net.
some 10800 IN CNAME some-site-3dd78f.netlify.com.
home 10800 IN A 33.33.33.33
ns 1800 IN NS test.com
pdf 1800 IN NS test.com
pop 10800 IN CNAME access.mail.provider.net.
smtp 10800 IN CNAME relay.mail.provider.net.
webmail 10800 IN CNAME webmail.provider.net.
```

**Comment by jayjb** [comment]
So the one thing I notice there is that you haven't added the NS records for this zone. The NS records (or Name Server records) are responsible for telling us which DNS server is our authoritative for that domain. For looking at your zone, you would need to add:

`@ 10800 IN NS ns1.provider.net
@ 10800 IN NS ns2.provider.net`

Something like that. Basically an NS record pointing test.com at the value in your SOA (`ns1.provider.net`).. You can also drop the TTLs on records for testing purposes.

**Comment by adrienpessu** [comment]
Thank you. Now, I think I have something in the log that will give us another clue : 
`'Error in render GET: No Canarytoken found in /hub/msmint/purgecache'`

I have regenerated DNS token and AWS token just to be sure that it should exist.

**Comment by jayjb** [comment]
@adrienpessu,

I can see you triggering the AWS API key Canarytoken; but it is failing the lookup. If i try lookup that domain, it also fails for me.

**Comment by adrienpessu** [comment]
So, as it turns out, my domain's name provider has trouble with setting NS records directly in the zone. It is seen as external. 🤷‍♂️
So I tried with another domain that I have in google domains and google don't want me to add NS records when I use google DNS. I guess google will add it automagically

`nslookup test.com` seems to work and `nslookup 6am6xml3cxmovmzqx2aq5ovdh.test.com` too

**Comment by jayjb** [comment]
Hi @adrienpessu,

How has the debugging going? Let me know if I can help you anywhere again

**Comment by adrienpessu** [comment]
Hi @jayjb 

I didn't successed yet. And to be honest, I don't know what to try. I am not sure to know how it works. Correct me, if I am wrong. When someone run : `host 8xqxlets30dgqtgn4r4l3bf5w.test.com`, the DNS server should should resolve this and send the request to `honeypot` switchboard, because the DNS record `@ 10800 IN A 66.66.66.66`. I don't know what is the purpose of  `ns 1800 IN NS test.com`.

Thank you very very much for your help.

**Comment by jayjb** [comment]
Hi @adrienpessu,

So i would say in terms of testing, run the tests along side the `canarytokens.org` site. This would give you an accurate account of what your should be seeing. 

1. Generate DNS token on canarytokens.org and run `host xxxxxxxxx.canarytokens.org` and make not of the results (email received and response from the server)
2. Generate DNS token on your sever and run `host xxxxxxxxx.test.com` and compare the results. 

The NS records are indicators of which DNS server is authoritative for that domain. As an example for AWS's Route53 DNS provider (and often its similar on other DNS providers too) if we have the domain `test.com`; AWS will tell you the nameservers responsible for `test.com` and these will be your NS records for `test.com`. In the same zone file for `test.com`, you will have an A records pointing towards the IP of your server. 

Please let me know what is still going wrong and we can attack that specifically.
