### ISSUE TITLE
Incident list drop down not expanding

### ISSUE THREAD

**Issue by sfuthings** [thinkst/canarytokens-docker#64]
I have tried Chrome, firefox and Safari and non of them can expand the Incident list nor the Export menu. Tried both docker version and the public web site (canarytokens.org)

**Comment by jayjb** [comment]
@sfuthings thanks for reporting it. We have fixed the issue. It was in the canarytokens repo.

**Comment by rogers421** [comment]
I think this issue has only been fixed for the public website and not the docker version .please help ,i'm trying out canary tokens through docker installation and the incident list is not expanding
