### ISSUE TITLE
Tried both SendGrid & MailGun API keys with no luck..

### ISSUE THREAD

**Issue by a6du114h** [thinkst/canarytokens-docker#66]
Hi, i've recently been testing this project but i'm having issues with the email alerts as i've tried both Sendgrid and mailgun so ive been wondering where i am going wrong?

For sendgrid do you use the smtp relay or the web api?

i have tried both in the switchboard.env with no luck 

Is there any guides to help?

Thanks

**Comment by jayjb** [comment]
Hi @a6du114h,

For sendgrid, you can check how we use it [here](https://github.com/thinkst/canarytokens/blob/b4a01381d6264ca6e64a7706c8d9996acc5941c6/channel_output_email.py#L174); it looks to be the API through their python client. 

For mailgun, please ensure that you supply both your API key and the correct mailgun domain; if you are sure you have, you can check the logs by running `docker exec -ti switchboard /bin/bash` and then `tail -f switchboard.log`. Once you trigger the token, you should see a log line about alerting (via email).

Please let me know how it goes (also there is more documentation over [here](https://docs.canarytokens.org/)).

**Comment by ch40s** [comment]
@jayjb @a6du114h 

I have the same issue. I use SendGrid, I have supplied the API key in `switchboard.env` (with and without quotes) and there is no entry in `switchboard.log` about an email notification when the token is triggered. I see this error might be related to that: `[_GenericHTTPChannelProtocol,4,IP] 'Exception occurred in switchboard dispatch: '`

**Comment by jayjb** [comment]
@ch40s that is a useful find. Ill see if i can get my hands on a Sendgrid api key and track down this issue.

**Comment by jayjb** [comment]
Hi @ch40s, @a6du114h 

Currently the Sendgrid API is working for me. I've removed all `MAILGUN` switchboard.env keys and left only the `CANARY_SENDGRID_API_KEY=SG.xxxxxxxx-xxxxxxxxxxxxxxxxxxx`. Please can you give me some more information about the Sendgrid API setup you used
