### ISSUE TITLE
Getting the real ip with the hook

### ISSUE THREAD

**Issue by nodauf** [thinkst/canarytokens-docker#67]
Hello,
When the canarytoken is triggers, I use the hook functionnality. In the additional_data -> src_ip it's the docker ip address instead of the client ip address: 172.18.0.1
You can find an example [here](https://requestbin.com/r/envvutakid6xd/1ezXFCo9AzuaC3SVwq5T8kQA0g5)

How can I get the real ip address?

**Comment by jayjb** [comment]
Hi @nodauf,

Sorry to hear your having some trouble. Would you mind supplying me with some more information about your setup? And how you triggered the Canarytoken? (I see it was some sort of HTTP token so it wouldn't grab the DNS server IP).

**Comment by nodauf** [comment]
Hi, 
thank you for taking the time to reply.
I have deployed the canarytoken with docker on a centos server.

During the generation of the token I specify the requestbin url as a hook parameter.
In this case I use the docx token but I also test with url token, to triggered the Canarytoken. I have open the doc file on a PC in the same subnet than the server. The IP sent to the web hook is an ip in the docker network. My network was 10.0.0.0/24

Feel free to ask if I missing something
Hope this explanation helps.

**Comment by nodauf** [comment]
I resolved my issue by stopping firewalld and using iptables.
I will try to find a solution with firewalld and post it in this issue

**Comment by nodauf** [comment]
With firewalld, I have resolved my issue by adding the new interface related to the new docker network to the trusted zone:
`firewall-cmd --zone=trusted --add-interface=br-b630d7256e36 `
