### ISSUE TITLE
Name resolution with systemd-resolved disabled - mailgun?

### ISSUE THREAD

**Issue by frekn0** [thinkst/canarytokens-docker#72]
I have got the docker container working, with both ssl and auth - after implementing suggested workaround in isssue 29. However, mailnotifications doesn't seem to work. Is that because the workaround in issue 29 breaks name resolution within container? I tried to verify by connecting (shell) to container and see signs that resolution fail, but it might not be a valid test!?

**Comment by jayjb** [comment]
Hi @frekn0,

Im sorry you having some issues with your Canarytokens setup. I hope I can help. Would you mind providing me with a little bit of info about your current setup? i.e. where you trying to run it? which mail service you trying to use? As much info as you can would be awesome.

Thanks

**Comment by frekn0** [comment]
Hi @jayjb !

Thank you so much for your quick response and sorry for  going light on the details :/ 

Canarytokens-docker is running on a Digital Ocean droplet (Ubuntu 18.04). I set off trying to use Mailgun for notifications of canary action. Configuration files attached below. Started off with the aforementioned tcp53 error upon launch, got that resolved to access /generate and can review Canary history. No notification when canaries trigger though.

frontend.env
--------------
CANARY_DOMAINS=mydomain.com
CANARY_NXDOMAINS=avjyd.mydomain.com

#CANARY_GOOGLE_API_KEY=

CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads
#Enter number so 1024*1024*10 = 10485760
CANARY_MAX_UPLOAD_SIZE=10485760

LOG_FILE=frontend.log

swithcboard.env
------------------
CANARY_MAILGUN_DOMAIN_NAME=mydomain.com
CANARY_MAILGUN_API_KEY=my_mailgun_api_as_provided_MG_WebUI
#CANARY_MANDRILL_API_KEY=
#CANARY_SENDGRID_API_KEY=
CANARY_PUBLIC_IP=droplet public IP
CANARY_PUBLIC_DOMAIN=mydomain.com

CANARY_ALERT_EMAIL_FROM_ADDRESS=
CANARY_ALERT_EMAIL_FROM_DISPLAY=
CANARY_ALERT_EMAIL_SUBJECT=
#CANARY_IPINFO_API_KEY=

CANARY_TOKEN_RETURN=fortune

CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads

LOG_FILE=switchboard.log

# Default protocol to use in notification links. If you don't use LetsEncrypt, set to http
PROTOCOL=https

**Comment by jayjb** [comment]
Hi @frekn0,

Thanks for the info. Its very useful. So i dont see anything obviously wrong with the config so I think its worth us doing a little debugging (im sure we will figure it out quickly!).

So i think we can start to narrow down the issue:
1. Lets check whether we are seeing any errors when the server tries to send the mail. The following steps should suffice.
a) ssh into your Canarytokens Server.
b) `sudo docker exec -ti switchboard /bin/bash`
c) `tail -f switchboard.log` 
d) create a token on your Canarytokens Server and trigger it. 
You should see the logging in the switchboard; the request coming in and the server handling that request. It should also tell you about alerting. Would you mind checking there if there is an exception showing up?

**Comment by frekn0** [comment]
Hi @jayjb 

Thanks again for being so responsive! I will provide update shortly when triggering a token, but notice at once that the name resolution issues I alluded to surface in the log as well:

[...)
        Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: check.torproject.org.

Cheers,
Fredrik

**Comment by jayjb** [comment]
Hi @frekn0,

Sorry for the delayed response. 

There are two quick checks please:
1) `sudo docker exec -ti switchboard /bin/bash` and then try resolve an external HTTP address such as `ping google.com` or `host mailgun.com` which would tell you whether that docker instance has external connectivity.
2) Looking over your config files; I see you hadnt input any mail information. In order for the mail capability you would need to supply those details.

**Comment by jayjb** [comment]
Hi @frekn0,

Thanks for the additional information. That looks promising (in terms of a test). I recall an issue simillar to this happening before. 

Would you mind trying [this](https://github.com/thinkst/canarytokens-docker/issues/29#issuecomment-425433315)?

**Comment by jayjb** [comment]
Hi @frekn0,

Let me know if you came right with the suggested solution please?

**Comment by jayjb** [comment]
Closing this issue because we haven't heard back. @frekn0 can reopen when they would like to continue discussing.
