### ISSUE TITLE
Certbot cannot be installed.

### ISSUE THREAD

**Issue by ch40s** [thinkst/canarytokens-docker#73]
The command `docker-compose -f docker-compose-letsencrypt.yml up` fails with the following error:

```
Skipping bootstrap because certbot-auto is deprecated on this system.
WARNING: couldn't find Python 2.7+ to check for updates.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.
ERROR: Service 'nginx' failed to build : The command '/bin/sh -c ./certbot-auto --install-only -n' returned a non-zero code: 1
```

I think the latest `certbot` version is required, so the current instructions and configuration are broken.

**Comment by ch40s** [comment]
I think we have two options:

1. Install certbot in the container and obtain a certificate each time which is not ideal. This can be done with a few modifications in Dockerfile (install certbot) and the start.sh file (use certbot instead of certbot-auto).
1. Get the certificates on the host and mount the necessary volumes to the container. 
Step 1 - Obtain the certificates:
`sudo docker run -it --rm --name certbot -v "/etc/letsencrypt:/etc/letsencrypt" -v "/var/lib/letsencrypt:/var/lib/letsencrypt" -p 80:80 certbot/certbot certonly`
Your certificate, chain and key file will  be saved in `/etc/letsencrypt/live/`.  
Step 2 - Modify the `certbot-nginx/nginx.conf` file to listen on 443 and use the new certificate and key. 
Step 3 - Modify `docker-compose-letsencrypt.yml` for the `nginx` service to mount the necessary directories and files as read-only:
```
    volumes:
    - /etc/letsencrypt/:/etc/letsencrypt/:ro
    - /etc/ssl/ffdhe4096.pem:/etc/ssl/ffdhe4096.pem:ro
    - canarytokens-docker/certbot-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
``` 
I had to do a few more changes in `start.sh` and `Dockerfile` to make that work.

**Comment by jayjb** [comment]
Hi @ch40s,

Thanks for reporting this. We will take a look and get back to you. We do know about the "get new certificate each time" issue and we just havent got to optimising for it yet.

**Comment by jayjb** [comment]
Hi @ch40s,

You mention that you have a working copy. We would love a PR if you have the time to submit one. We always appreciate folks contributing.

**Comment by hostinger-free** [comment]
Confirming, I get the same error. Still a problem.

**Comment by hostinger-free** [comment]
I just fought thru the errors --  but now there's a SSL error "SSL_ERROR_RX_RECORD_TOO_LONG" -- possibly not updated TLS. I'll submit an issue tomorrow when I get a chance -- also what changes I made to get it working (almost)

**Comment by joshhighet** [comment]
A potential solution

certbot's `--keep-until-expiring` should stop any excessive issuance/renewals

> certbot/Dockerfile
```dockerfile
FROM nginx
RUN apt-get update
RUN apt-get install -y python-certbot-nginx procps
COPY nginx.conf /etc/nginx/nginx.conf
COPY start.sh /
RUN chmod +x start.sh
CMD /start.sh
```

> certbot/start.sh

(replacing example.com accordingly)

```shell
sed -i "s/___server_names___/example.com/g" /etc/nginx/nginx.conf
nginx
sleep 5
certbot --nginx --email you@example.com -d example.com --agree-tos --redirect --no-eff-email --keep-until-expiring --non-interactive
nginx -s stop
sleep 3
nginx -g "daemon off;"
```

**Comment by jayjb** [comment]
Hi folks, 

Sorry for the delay in getting this sorted. I've updated the Dockerfile and some other stuff to fix this issue. Please let me know if you have more issues like this. Ill be closing the issue for now.
