### ISSUE TITLE
ipinfo.io gives 404 with src_ip has two ip values on log with comma separated string as 94.121.155.184,162.158.18.150

### ISSUE THREAD

**Issue by jaswinder97** [thinkst/canarytokens-docker#79]
Here is a request log:

`'Error getting geo ip: ipinfo.io response was unexpected: <Response [404]>'
switchboard    | 2021-01-16 10:38:47+0000 [HTTPChannel,0,172.18.0.5] {'src_ip': '94.121.155.184, 162.158.18.150', 'useragent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36', 'referer': None, 'location': None}`

Now, if we use any of these IP as 
`https://ipinfo.io/94.121.155.184/json`

It gives proper json response:
`{
  "ip": "94.121.155.184",
  "city": "Diyarbakır",
  "region": "Diyarbakır",
  "country": "TR",
  "loc": "37.9136,40.2172",
  "org": "AS12978 DEMIROREN TV DIGITAL PLATFORM ISLETMECILIGI A.S.",
  "postal": "21070",
  "timezone": "Europe/Istanbul",
  "readme": "https://ipinfo.io/missingauth"
}`

But the 404 error might be due to 'src_ip': '94.121.155.184, 162.158.18.150' in URL like 

`https://ipinfo.io/94.121.155.184,162.158.18.150/json`

which gives :
`{
  "status": 404,
  "error": {
    "title": "Wrong ip",
    "message": "Please provide a valid IP address"
  }
}`

How to resolve this issue?

**Comment by jaswinder97** [comment]
@ycparak do you anything about it? could you please help me to resolve this?

**Comment by jaswinder97** [comment]
@jayjb do you have some time on this please?

**Comment by jayjb** [comment]
Hi @jaswinder97,

Sorry for the delayed response. Thats a good find. It doesnt look like ipinfo.io supports comma separated IP addresses. This fix would need to be made in the `canarytokens` repository. Basically a check for if we comma separate, is there more than two items, if so, send them through to ipinfo.io individually.

**Comment by emmanuel-thinkst** [comment]
Dear @jaswinder97 

Sorry for the delayed response. We have recreated the issue and confirmed that it has been resolved in our `canarytokens` `V3`. Please pull the latest changes from our `master` branch and run our `V3` dockerized canarytokens

Thank You.

**Comment by emmanuel-thinkst** [comment]
Dear @jaswinder97 

Sorry for the delayed response. We have recreated the issue and confirmed that it has been resolved in our `canarytokens` `V3`. Please pull the latest changes from our `master` branch and run our `V3` Dockerized Canarytokens

Thank You.
