### ISSUE TITLE
Fail2ban

### ISSUE THREAD

**Issue by school-j** [thinkst/canarytokens-docker#86]
I am trying to implement fail2ban for nginx, but I cannot find any log files that canarytokens references. When I search in etc, nginx isn't even a folder there. Any suggestions on where nginx log files are that fail2ban can reference?

**Comment by jayjb** [comment]
Hi @school-j,

When you say you are looking for nginx log files in `/etc`, is that on the host machine or in the docker container? Usually log files are output into `/var/log` but I suspect those would be in the relevant container and not in the host machine

**Comment by school-j** [comment]
I see in the docker compose, there is an area for logs to be written at the bottom.
