### ISSUE TITLE
Error while running docker-compose up

### ISSUE THREAD

**Issue by Manu-Surendra** [thinkst/canarytokens-docker#9]
This is the error i get when i run while running docker-compose up

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-P5Plug/twilio/
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c pip install --no-cache-dir twilio==4.4.0' returned a non-zero code: 1

**Comment by thinkst** [comment]
Hi,

We have just pushed new docker images to sort out this issue (in fact, they were being pushed as you sent that comment).

If you pull the latest images and try again, the issue should be sorted.

**Comment by Manu-Surendra** [comment]
Hey thanks man, it worked

**Comment by phongiswindy** [comment]
There were some RED lines (errors?) appear while running `docker-compose up`

> debconf: delaying package configuration, since apt-utils is not installed
> You are using pip version 8.1.1, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

They may not be fatal errors but I think should be addressed in future update.
