### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by mrrobotnl** [thinkst/canarytokens-docker#96]
Dear developers, 
I am currently prototyping open canary in my test environment, is it perhaps possible to use a self-signed certificate? And is there possible an instruction to get this working?

**Comment by jayjb** [comment]
Hi @mrrobotnl,

Which service would you like to use the self signed certificate for? Currently we dont have anything that allows that but I'd be interested to know where you would like to use it and maybe we can make it happen.. Alternatively, we always encourage folks to submit PRs and would be happy to discuss/help with it?
